### ISSUE TITLE
RPC Response structure can probably be improved?

### ISSUE THREAD

**Issue by 524119574** [michaelhly/solana-py#10]
Currently if I do:
```
http_client = Client("https://api.mainnet-beta.solana.com")
marketAddress = PublicKey('6ibUz1BqSD3f8XP4wEGwoRH4YbYRZ1KDZBeXmrp3KosD');
print(http_client.get_balance(marketAddress))
```
The result sill be:
```
{'jsonrpc': '2.0', 'result': {'context': {'slot': 30942520}, 'value': 3535680}, 'id': 1}
```
However, this is not desirable since the user will still need to know what is the format of the RPC response. I think it's probably better if we can have something similar to what the js client is doing, i.e. having a type that is similar to:
```
export type RpcResponseAndContext<T> = {
 context: Context;
 value: T;
};

```

**Comment by michaelhly** [comment]
Won't do for now.
