### ISSUE TITLE
Bump Solana docker image for integration tests

### ISSUE THREAD

**Issue by michaelhly** [michaelhly/solana-py#116]
Bump
https://github.com/michaelhly/solana-py/blob/b3855f39f25bd632f78c9f33c4bcd15a574b3320/tests/docker-compose.yml#L4
to 1.7.x

**Comment by kevinheavey** [comment]
To save anyone else time on this, it seems the 1.7.x Docker images are currently broken. If I run the code from the `test_token` fixture against v1.7.8 using the Solana CLI, it works fine. But if I run against the 1.7.8 Docker image we get the `InvalidAccountData` errors.

Separately, the more recent 1.7.x images are broken for some other reason. Raised an issue here https://github.com/solana-labs/solana/issues/20692
