### ISSUE TITLE
Use getHealth rpc method instead of /health URL

### ISSUE THREAD

**Issue by zpalmtree** [michaelhly/solana-py#119]
Hello,
I was wondering if it would be possible to update the `is_connected` check to hit the [getHealth](https://docs.solana.com/developing/clients/jsonrpc-api#gethealth) json RPC method, instead of the `/health` URL?

I have a node from quicknode, which returns a 404 for the `/health` call, but supports the `getHealth` rpc method.

Thank you.

**Comment by michaelhly** [comment]
Looks like this is blocked by https://github.com/michaelhly/solana-py/issues/116 :(

**Comment by mp-freatic** [comment]
This should be closed now thanks to the merge of https://github.com/michaelhly/solana-py/pull/460 :) 
@zpalmtree @michaelhly
