### ISSUE TITLE
Generate Keypair from mnemonic words that works on Phantom etc...

### ISSUE THREAD

**Issue by brunopedrazza** [michaelhly/solana-py#123]
When I create a Keypair from a seed generated form a mnemonic phrase and import it to Phantom or Solong, the public key is completely different from the one from Keypair.public_key. Here is a code snippet:

``` python
mnemo = Mnemonic("english")
words = mnemo.generate(strength=256)
seed = mnemo.to_seed(words)

keypair = Keypair.from_secret_key(seed)
public_key = keypair.public_key
```

Does anyone know how to use the Keypair object from solana-py compatible with other wallets?

**Comment by thinkingparticle** [comment]
I did the same as your steps. Then took the hex of `keypair.secret_key` and imported the hex in phantom and wallet address showed the same `public_key` as in python 

`keypair.secret_key.hex()`
