### ISSUE TITLE
generate derived seed from mnemonic

### ISSUE THREAD

**Issue by spankders** [michaelhly/solana-py#134]
hello
so i was using this solana-py keypair method to generate a public and private key from seed
i generated the seed from a spesific mnemonic
but when i try to compare the result public key of solana-py to phantom wallet public key
and it was a whole different address

i was wondering if there is a way to change the derivation of the seed to the path phantom wallet uses instead of using the default path

**Comment by brunopedrazza** [comment]
#123 can help you
