### ISSUE TITLE
getBlock, getBlocks, getTransaction

### ISSUE THREAD

**Issue by 02agarwalt** [michaelhly/solana-py#137]
I see solana.rpc.api.Client supports functions getConfirmedBlock/Blocks/Transaction, but these have been deprecated by the official JSON RPC api. Could this repo add functionality for the new functions getBlock/Blocks/Transaction?

I can submit a pull request if that is acceptable.

**Comment by michaelhly** [comment]
@02agarwalt. Yes, feel free to submit a PR.

**Comment by 02agarwalt** [comment]
I've created the pull request, but am unable to link it to this issue tracker.

**Comment by 02agarwalt** [comment]
PR merged.
