### ISSUE TITLE
lint C0209: Formatting a regular string which could be a f-string

### ISSUE THREAD

**Issue by broper2** [michaelhly/solana-py#140]
Great project, been using for a bit creating backend around Solana data.

Also looking to contribute a bit, I see this complaint from "make lint" tests, thought it would be a good first issue to dive in with.

Is it cool if I raise a PR migrating these string formats to f-strings?

**Comment by michaelhly** [comment]
@broper2 yes please!

**Comment by broper2** [comment]
have raised PR for this
