### ISSUE TITLE
Execute transactions on DEX with solana-py

### ISSUE THREAD

**Issue by gabrielfior** [michaelhly/solana-py#142]
Is it possible to execute swaps using solana-py? If yes, can someone please point me to an example of a working code?

**Comment by michaelhly** [comment]
Which dex? Might look into using https://github.com/kevinheavey/anchorpy

**Comment by gabrielfior** [comment]
@michaelhly thanks for the reference! I was looking into Serum, for that I found pyserum (https://github.com/serum-community/pyserum) but there it's not possible to execute swaps. Hence I'm looking for an alternative.
I believe anchorpy could be a candidate, since I can interact directly with the contract, however if there was a wrapper for that it would be a dream.
