### ISSUE TITLE
invalid transaction: index out of bounds

### ISSUE THREAD

**Issue by spankders** [michaelhly/solana-py#156]
im trying to make a transaction but i get this error in the title

the code im using is :
```
import binascii
from bip_utils import Bip44Coins, Bip44, Bip39SeedGenerator, Bip44Changes, Base58Encoder
from solana.keypair import Keypair
from solana.transaction import Transaction, TransactionInstruction, AccountMeta
from solana.system_program import TransferParams, transfer
from solana.rpc.api import Client
from mnemonic import Mnemonic


seed_bytes = Bip39SeedGenerator("man canoe coffee strong mixed income return muscle sauce install turn urban").Generate()

bip44_def_ctx = Bip44.FromSeed(seed_bytes, Bip44Coins.SOLANA)
bip44_acc_ctx = bip44_def_ctx.Purpose().Coin().Account(0)
bip44_chg_ctx = bip44_acc_ctx.Change(Bip44Changes.CHAIN_EXT)
print("phantom derived public key: "+bip44_chg_ctx.PublicKey().ToAddress())

pub_key = bip44_chg_ctx.PublicKey().RawCompressed().ToBytes()[1:]
priv_key = bip44_chg_ctx.PrivateKey().Raw().ToBytes()

print("phantom derived private key: " + Base58Encoder.Encode(priv_key + pub_key))


sender_keypair = Keypair.from_secret_key(seed_bytes)



txn = Transaction()
txn.add(
    transfer(
        TransferParams(
            from_pubkey='BccQxxd2Lh9WL2L8YgoGp6kSZERRRjgvn8efV6gmMU2y',
            to_pubkey='4kaa7iTYLxTjKErWwnMD17LnQpMEhRC9mmdbQR11w8ZQ',
            lamports=5000
        )
    )
)
solana_client = Client('https://api.devnet.solana.com')
tx_data = solana_client.send_transaction(txn, sender_keypair)
print(tx_data['result'])
```

i used bip_utils library since the original solana-py library generate public key but for a different path than the one used on a phantom wallet
public and private key is fine but when it comes to sending the transaction i get the index out of bounds error

**Comment by SubstructureDek** [comment]
I ran into this error when I was signing a transaction with the wrong keypair. The "cull duplicate" code-block in `Transaction.compile_message` was finding the extra pub key and creating an additional `AccountMeta` for it, and then setting `num_required_signatures` to 2 when there was only 1 signature (and only 1 AccountMeta with `is_signer=True` in the ones I had explicitly initialized). Didn't debug beyond that since I recognized the error but guessing the `num_required_signatures == 2` in the `MessageHeader` when only one signature was provided is what led to the index error.

**Comment by spankders** [comment]
thank you for your reply
what im trying to do is send a transaction for a different public key which is generated from the same seed on a different derivation path
i managed to get the derived public key and its own private key however the previous key pair doesnt seem to work so the solution might be generating the keypair from the new public and private keys which i have no clue how since the only way to generate a key pair is from the seed

**Comment by roks0n** [comment]
I believe the issue is that `bip_utils`'s seed is long 64 bytes while `Keypair` uses `nacl` library which only uses the first 32 bytes. Because of this there's no way to correctly sign this transaction as far as I'm aware?

**Comment by michaelhly** [comment]
This issue should be resolved since we migrated to [Solders](https://github.com/kevinheavey/solders).
