### ISSUE TITLE
duplicate signers in send_transaction will result in an opaque UnconfirmedTxError

### ISSUE THREAD

**Issue by phubaba** [michaelhly/solana-py#171]
For example if you run code like:
```
authority = Keypair()
result = client.send_transaction(Transaction(...), authority, authority) 

```
this will create the UncofirmedTxError.

Should we add a sanity check say in solana/transaction.py", line 235, in sign_partial

```
if len(set(partial_signers)) != len(partial_signers):
       raise ValueError('duplicate signers will fail')
```

Then a more clear error will be raised.

**Comment by crypt0miester** [comment]
> For example if you run code like:
> ```
> authority = Keypair()
> result = client.send_transaction(Transaction(...), authority, authority) 
> 
> ```
> this will create the UncofirmedTxError.
> 
> Should we add a sanity check say in solana/transaction.py", line 235, in sign_partial
> 
> ```
> if len(set(partial_signers)) != len(partial_signers):
>        raise ValueError('duplicate signers will fail')
> ```
> 
> Then a more clear error will be raised.

authority should be in a list 

```
result = client.send_transaction(Transaction(...), *[authority, authority]) 
```
