### ISSUE TITLE
__hash__ on PublicKey and Keypair

### ISSUE THREAD

**Issue by quazzuk** [michaelhly/solana-py#173]
Can `__hash__` perhaps be added to the `PublicKey` and `Keypair` classes to allow them to be used as keys of dictionaries and in sets?

Thanks

**Comment by michaelhly** [comment]
`Keypairs` are hashable since v0.2.0: https://github.com/michaelhly/solana-py/blob/master/CHANGELOG.md#changed-1

**Comment by quazzuk** [comment]
Awesome. I'll raise a PR for the change on `PublicKey`
