### ISSUE TITLE
speed of (light) send_transaction 

### ISSUE THREAD

**Issue by Nikita-Efimov** [michaelhly/solana-py#174]
is it possible to speed up send_transaction?

**Comment by michaelhly** [comment]
Can you provide more details? Also have you tried the async client?

**Comment by Nikita-Efimov** [comment]
so i mean some minor things like skip_preflight=False change to better rpc, what i can do to speed up send_transaction

**Comment by aleixisp** [comment]
`send_transactions` just broadcast the transaction to the blockchain, if the transaction is processed, you can expect around 12.5 seconds (`confirmation=Finalized`) to be fully acknowledged. The set of options in the SDK are meant to have feedback in the same call. You can set the threshold to `confirmation=Confirmed` which its status is gonna change to `finalized` in the next 8-10 seconds
If in `send_transaction` you set `skip_confirmations=False` the max time to wait for response can be up to 30sec + your timeout definition (`max_timeout`). However, you can set up your own logic to catch the response by scanning the blockchain using the signature hash.

Hope that helps.
