### ISSUE TITLE
abount batch transfer

### ISSUE THREAD

**Issue by lly835** [michaelhly/solana-py#175]
`{'code': -32602, 'message': 'invalid transaction: index out of bounds'}`

```
    transferParams = TransferParams(from_pubkey=sendPublicKey, to_pubkey=PublicKey('to_address1'), lamports=amount)
    trs = transfer(transferParams)

    transferParams = TransferParams(from_pubkey=sendPublicKey, to_pubkey=PublicKey('to_address2'), lamports=amount)
    trs2 = transfer(transferParams)
    
    txn = Transaction().add(trs, trs2)
    res = solana_client.send_transaction(txn, signer)
```

**Comment by crypt0miester** [comment]
> `{'code': -32602, 'message': 'invalid transaction: index out of bounds'}`
> 
> ```
>     transferParams = TransferParams(from_pubkey=sendPublicKey, to_pubkey=PublicKey('to_address1'), lamports=amount)
>     trs = transfer(transferParams)
> 
>     transferParams = TransferParams(from_pubkey=sendPublicKey, to_pubkey=PublicKey('to_address2'), lamports=amount)
>     trs2 = transfer(transferParams)
>     
>     txn = Transaction().add(trs, trs2)
>     res = solana_client.send_transaction(txn, signer)
> ```

this should be .add(trs).add(trs2) instead of add(trs, trs2)
