### ISSUE TITLE
Using publickey.PublicKey().find_program_address() getting NotImplementedError

### ISSUE THREAD

**Issue by CryptoUncleSam** [michaelhly/solana-py#180]
Hello guys!

I am try to get PDA for a mint address for later que metadata for NFTs but when I use the function I am getting that error!

Probably I am using wrong the function. I really do not know.

Thanks before hand.

`from solana.publickey import PublicKey

METADATA_PROGRAM_ID = PublicKey('metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s')
mint_key = "8Rjxaxy8ZNAGTojzQSAMSPatNiop9C9PRPY5A29qhrCT"

PDA = PublicKey.find_program_address(
        [b'metadata', bytes(METADATA_PROGRAM_ID), bytes(PublicKey(mint_key))],
        METADATA_PROGRAM_ID
    )[0]

print(PDA)`

**Comment by michaelhly** [comment]
Which version of solana-py are you using?

**Comment by CryptoUncleSam** [comment]
Yes it was version of solana-py!

Just update is working now!

Thanks!
