### ISSUE TITLE
sign_partial method removing previous signatures

### ISSUE THREAD

**Issue by ciroartz** [michaelhly/solana-py#182]
Hello, I've just came across an error on solana py: whenever I use the sign_partial function, it deletes the previous signatures, causing the whole transaction to fail, I'm 100% sure as I just verified by myself and this is what happened:

`Before Partial Sign  [SigPubkeyPair(pubkey=4droyY5MVemmoajaMpSfapvxdYUzTmHnzRm3JLRiMXjV, signature=None), SigPubkeyPair(pubkey=6xaXdenPUDKDQLfqGKyhUgvoMJmMNeUCB4hdj9YrnznG, signature=None), SigPubkeyPair(pubkey=71e43w8efa2H6T3pQR7Hif8nj5A3ow2bnx6dAzYJBccP, signature=None)]`

`After Partial Sign  [SigPubkeyPair(pubkey=6xaXdenPUDKDQLfqGKyhUgvoMJmMNeUCB4hdj9YrnznG, signature=b'U\x94\x92\xbe\x99w\xd2\x8b\x93\xc76\xd7\xaaWH\xdbL{\xcd\xa3u\x06\x1f\xc6\xd8\x99M\x96g\x1a\xab\xa3\x0b%\x00\x05\xc8d\xefv\xb3g8L\x1b\xa8\x14@\x9c\xe6iB\xb18H\xb4\xbc\xc3\xf1\xbaH,y\x02')]`

I'm using the latest version of solana-py.

**Comment by robinvangenechten17** [comment]
add_signer is what you are trying to do :)

**Comment by robinvangenechten17** [comment]
Updating solana.py will resolve these issues too!
