### ISSUE TITLE
ModuleNotFoundError: No module named 'solana.rpc'; 'solana' is not a package

### ISSUE THREAD

**Issue by ThiagoMathiaz** [michaelhly/solana-py#183]
The code example isnt working...
solana lib alredy installed.

`Traceback (most recent call last):
  File "/home/ubuntu/projects/solana/aa.py", line 1, in <module>
    from solana.rpc.api import Client
  File "/home/ubuntu/projects/solana/solana.py", line 2, in <module>
    from solana.rpc.async_api import AsyncClient
ModuleNotFoundError: No module named 'solana.rpc'; 'solana' is not a package`

**Comment by kevinheavey** [comment]
This works, it's likely some problem with your Python environment. Hopefully it's a simple problem :(
