### ISSUE TITLE
Deserialize account data given an anchorlang IDL?

### ISSUE THREAD

**Issue by AlphaPrime8** [michaelhly/solana-py#185]
I am new to the cstruct deser method, I see this framework has implemented solutions for system program ix data deser. Can someone point me in the right direction how to extend this to any account data given an IDL?

**Comment by michaelhly** [comment]
Please checkout https://project-serum.github.io/anchor/getting-started/introduction.html

**Comment by iamashwin99** [comment]
This unfortunately no longer supports recent versions of Anchor :(
