### ISSUE TITLE
Validate solana wallet address?

### ISSUE THREAD

**Issue by mojalil** [michaelhly/solana-py#186]
Hi all, 

I have a huge list of wallet addresses (10's of thousands) and would like to validate which ones are solana addresses. Any way to do this in python ?

**Comment by michaelhly** [comment]
There is validation here:
https://github.com/michaelhly/solana-py/blob/master/src/solana/publickey.py#L30-L46

**Comment by mojalil** [comment]
Thank you very much for replaying @michaelhly ! I'll take a look now.
