### ISSUE TITLE
Rate limits for AsyncClient

### ISSUE THREAD

**Issue by HenryHar** [michaelhly/solana-py#194]
Hey guys, first and foremost I really appreciate the SDK/wrapper you and the community have built.

I am wondering if there's an easy way to implement some rate limiting besides adding a blocking time.sleep call.  

I don't have much experience with async_http client so it could be from me but i have spent some decent time digging around. Thanks again for the wonderful wrapper

**Comment by crypt0miester** [comment]
hi, so you would use something like aiolimiter at the the top of your function. 

hope this helps.
