### ISSUE TITLE
Syntax error while installing in ubuntu

### ISSUE THREAD

**Issue by krishna-bhandari** [michaelhly/solana-py#207]
I am getting syntax error:
 `File "/home/krishna/.virtualenvs/env/lib/python3.6/site-packages/solana/rpc/api.py", 
line 2
    from __future__ import annotations
                                     ^
SyntaxError: future feature annotations is not defined`

**Comment by michaelhly** [comment]
@krishna-bhandari solana-py requires python3.7+
