### ISSUE TITLE
Subscribing to Serum-Dex fails?

### ISSUE THREAD

**Issue by Joe-Victor** [michaelhly/solana-py#209]
I'm not quite sure how to subscribe to the orderbook and trades for the serum-dex. I tried subscribing to the programId using:

import asyncio
from asyncstdlib import enumerate
from solana.rpc.websocket_api import connect
from solana.publickey import PublicKey

```
async def main():
    
    # Alternatively, use the client as an infinite asynchronous iterator:
    async with connect("wss://api.devnet.solana.com") as websocket:
        await websocket.program_subscribe(PublicKey("9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin"))
        print("subscribed...")

        async for idx, msg in enumerate(websocket):
            print(msg)

asyncio.run(main())
```

But what I get is:

```
subscribed...
Ok(result=5708326, id=1)
```

and nothing else afterwards. What am I missing here?

**Comment by michaelhly** [comment]
Can you try mainnet instead of devnet?

**Comment by Joe-Victor** [comment]
I switched to using serum-dex's api. That seemed easier. Thanks!

**Comment by michaelhly** [comment]
cc @kevinheavey
