### ISSUE TITLE
missing getRecentPerformanceSamples method

### ISSUE THREAD

**Issue by ennnas** [michaelhly/solana-py#218]
The library is missing the "newly" added method [getRecentPerformanceSamples](https://docs.solana.com/developing/clients/jsonrpc-api#getrecentperformancesamples)

Adding it to the library should be pretty straightforward since it's simply a new endpoint to support

**Comment by michaelhly** [comment]
FYI, you can also use the RPC providers directly to make requests :)

https://michaelhly.github.io/solana-py/rpc/providers/

**Comment by ennnas** [comment]
Yes, I implemented the missing endpoint with that. I can open a PR if you want. In general, is there a procedure for contributing to the repo? I was looking for a `CONTIBUTING.md` but didn't find any

**Comment by michaelhly** [comment]
We should add one. But in general, making sure the CI checks passes is fine, and also writing an integration test.
