### ISSUE TITLE
Typing-extensions constraint is restrictive

### ISSUE THREAD

**Issue by aerskine** [michaelhly/solana-py#219]
A large number of open source libraries have a typing-extensions constraint `>=4.0.0`, which unfortunately runs contrary to this packages `<4.0.0`

Since it is not a core dependency can we change the constraint from `^3.10.0` to `>=3.10.0`?

**Comment by michaelhly** [comment]
https://github.com/michaelhly/solana-py/commit/c1757c131f0a346be46f26262645b4b7ca8fa530

**Comment by jcranendonk** [comment]
Thanks for the change! Will you publish this update soon? It's blocking me from updating boto3-stubs to latest.

**Comment by michaelhly** [comment]
@jcranendonk will create a new release today!
