### ISSUE TITLE
AirDrop not working

### ISSUE THREAD

**Issue by yayago123** [michaelhly/solana-py#224]
For the past 12hrs or so, I have been unable to succesfully call solanaPyClient.request_airdrop().  The function returns successfully a valid looking json response.  However, the transaction never shows up in solexplorer.  And the balance of the wallet never changes.

This is code that worked yesterday and is now not working.   It has not been modified.

Scott

**Comment by michaelhly** [comment]
@yayago123 i think the solana devnet has been down ..

**Comment by mryalamanchi** [comment]
Solana devnet is seeing http 503 errors frequently!
