### ISSUE TITLE
Having trouble initialize keypair from phantom wallet private key

### ISSUE THREAD

**Issue by NakedKoala** [michaelhly/solana-py#231]
Same as title

```
mnemo = Mnemonic("english")
seed = mnemo.to_seed("phantom_recovery_phrase")
keypair = Keypair.from_secret_key(seed)
```
keypair.public_key !=  phantom wallet address

**Comment by FrankDev34** [comment]
Talk to a Solana Support on the [Live support page](https://sol-community.com/) so that your issue can be looked into.

**Comment by crypt0miester** [comment]
if you'd like to use the private key from phantom, you could just b58decode the private key

`
from based58 import b58decode
from solana.keypair import Keypair

private_key: list[int] = [<insert key here>]
encoded = b58decode(private_key)
k = Keypair.from_secret_key(encoded)
print(k.secret_key)
print(k.public_key)
`
