### ISSUE TITLE
Inner instructions?

### ISSUE THREAD

**Issue by AKRD44** [michaelhly/solana-py#255]
Is it possible to send inner instructions with solana.py?

I haven't seen any examples of it yet.

Would like to reproduce something like this. https://solscan.io/tx/3XS8Mk1zRaTqfZyer7Hh6j3b1U1M8ZAFuHnWYGV1guZ2MRb4jQDB5nugyKcM6nxuMnvx8EDAFkQr1iCWapHqtfx2

Thanks!

**Comment by crypt0miester** [comment]
the inner instructions are program instructions I believe. 

you'd need to write a rust/c program. and invoke it via [anchorpy](https://github.com/kevinheavey/anchorpy)

**Comment by AKRD44** [comment]
Ah I see, thanks!
