### ISSUE TITLE
send_raw_transaction(transaction.serialize())

### ISSUE THREAD

**Issue by robinvangenechten17** [michaelhly/solana-py#259]
transaction_response = client.send_raw_transaction(transaction.serialize())
{'code': -32002, 'message': 'Transaction simulation failed: Error processing Instruction 2: custom program error: 0xbc4', 'data': {'accounts': None, 'err': {'InstructionError': [2, {'Custom': 3012}]}
I get this error for like 20 seconds after an NFT is listed and found on the blockchain. After 20 seconds it seems to magically fix the problem on his own. Any idea how I can speed this up? I want to make a sniper and I am able to buy the NFT faster through Magic eden than through sending a transaction because it fails for like 20 seconds with this error.

**Comment by crypt0miester** [comment]
try declaring skip_preflight as True in TxOpts(skip_preflight=True).

if that did not work, you might want to sleep for 20 seconds. it is just that the account needs time in order for the data to be propagated in the blockchain.

```
0xBC4: 
        Anchor Program            |     AccountNotInitialized: The program expected this account to be already initialized
```
