### ISSUE TITLE
Sign str hash

### ISSUE THREAD

**Issue by dustiwe** [michaelhly/solana-py#263]
`AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAkb/Mo45PBWMkQWYC8OWj7q3KOKJSLT686lxJUK1wNM/boXiyxYhg+1nNjUAOhiOhg24Do8rEQ70Tei9RzCRYPafyyWTIIEB1v9ZarkN7Vti3nOlQ0LXajC3b2WNkMHQmT8LdtvWKRmL/gOQawe9cjHdbfXnd2dT1xcBS2fz0SgkdRNhB8sjw39LBhxw3yag4aguh1U3/0NQTNBTo29izoly1WkKgsZmXvQQFqhRD1JHuRZ5sGWynXhQ9iBbrccsTq0UA3K7UtR8sKyklEJU7BKCgr2a6eyKfq8iwZ7hcjWaEpaMTIlz85MaD/2vhQ8FgcFThAa1Arml20gDadXvwJV+HE5d5mMnOeZ4pOBglp/G1I/Y2WTKFLE0/kW39P3+cvslp/hY8GQcVwsxyrLd7ppgTbVEiV8fXGwtluVqyLSOaOgLXw1fvbvUiJR2QYDuOTF4vRf5T4mBfJnJLjxX9qjHLxKH8O1I3TEWDwfkiopP8eaiM1GdKRdymuO6QoDEmLuzDTZW2MX8/UOLRKIYBLSOhhLGnSa/JnVaiK7XDVAcK7c/ZbCjVML2pBETEv6G58L2wPHexakyw2Up445jKsEXOgx01QXXAIgIzyjYbzd7el0s6ZL7gY60mRniYrd2Ovv9pTYfat9JGy7emLIverMKiCNh8pQaC/hyJkIegVLI07/Yz1srb9OiKpwPYj/LaXxbLpyHIUv7TJArt40lPEQRf+fBWbhEsjrHYzE43rUyR0gLhbOyzlfOE5UiwZuqH4dQVewWA8xxfzkSmJYLbz5147nWUOghKOTs1A2jSKJkwhK1vRSYa/BAHwW96OXfE5V5EIzltPb/HyLy9vH0B4pnkvZScQ2AsM/IHeQ7RajUkyhuZdc8SGiqQz/7H34torNToDF6mLS+ouPT2NGXFQSraIA6AZPbbDmLDF4kSC8Vpx9h3NMA6nnqLYAkA2xg3mxfUOJ6znwuW9lisBTTjQYkn5UdxpXpvFMqeQC1UruRfc3iso2XHsWmn7IP1GCspjwhQ8tbgKkevgk0Jq2ncQtcMsoy/okn7fuV7nSVsEnYu8EedUfqc1K9verCrBuSC3GTDKNqlknKr4vTpiCV14OeAbd9uHXZaGT2cvhRs7reawctIXtX1s3kTqM9YV+/wCpNHzAHk5UnK2Q17e6QGwldD4+muWtKW4xUcjAGHPA+rgEGQIHBgjkVblwTk9NAhkLFxoVFgANAg4GBREau8B21D5tHNUBADgMIpAnAAAAAAAAAAAAAAAZEhQaDBIKEAEYAwkICw8EEw0GABpF42Jd7crfjAEAOAwikCcAAAAAAAAAAAAAABkEBwYAGhFRKrOY3QG1eMvXW9ghAAAAAA==`

I have this hash and I need to sign it, how can I do this? Do I need to somehow transfer this str to the transaction class?

**Comment by michaelhly** [comment]
Can you try https://michaelhly.github.io/solana-py/core/transaction/#solana.transaction.Transaction.populate

**Comment by dustiwe** [comment]
> Can you try https://michaelhly.github.io/solana-py/core/transaction/#solana.transaction.Transaction.populate or https://michaelhly.github.io/solana-py/core/transaction/#solana.transaction.Transaction.deserialize

from solana.rpc.api import Client
from solana.transaction import Transaction
solana_client = Client("https://raydium.rpcpool.com/") 
a = Transaction.deserialize(bytes.fromhex(str_hash))
a.sign()
print(solana_client.send_transaction(a))

`Traceback (most recent call last):
  File, line 5, in <module>
    a = Transaction.deserialize(bytes.fromhex(str_hash))
ValueError: non-hexadecimal number found in fromhex() arg at position 1
`

**Comment by dustiwe** [comment]
> Can you try https://michaelhly.github.io/solana-py/core/transaction/#solana.transaction.Transaction.populate or https://michaelhly.github.io/solana-py/core/transaction/#solana.transaction.Transaction.deserialize

This is not what I need, this hash that I have given above is not yet signed

**Comment by crypt0miester** [comment]
it is not a hex from the looks of it. 

I feel like it is base64. try decoding it first.

**Comment by kevinheavey** [comment]
@dustiwe can you try base64 decoding that data, then doing `my_keypair.sign(decoded)`?

**Comment by kevinheavey** [comment]
Closed as inactive
