### ISSUE TITLE
How to convert RPCResponse to Transaction data?

### ISSUE THREAD

**Issue by devlancer412** [michaelhly/solana-py#270]
I get transaction data with get_transaction function
```
result = solana_client.get_transaction(signature)
```
The result is RPCResponse data and I want to convert it to TransactionInstruction structure.

How I can do that.
I can't see anything associate that in solana.py docs

**Comment by crypt0miester** [comment]
I don't think one can do that. 

since the instructions has already been worked on. 

I believe TransactionInstructions can only be used with raw transactions in solana-py. 

good news that it is possible but you will have to parse account metas individually.

**Comment by devlancer412** [comment]
So there aren't any function to decode instruction data?
Main problem is to decode instruction data.
@crypt0miester 
Do you have any idea about it?

**Comment by crypt0miester** [comment]
it will need to be raw transaction to decode using solana py, before serialization.

try going through the explorer source code to get an idea how parsing propagated transactions is done.

**Comment by crypt0miester** [comment]
> explorer source code? where I can see that?

solana repo explorer folder.

**Comment by devlancer412** [comment]
awesome
