### ISSUE TITLE
AsyncToken.transfer transaction goes through, but throws "Unable to confirm" error

### ISSUE THREAD

**Issue by ZenRepublic** [michaelhly/solana-py#277]
Using AsyncToken.transfer method, I want to transfer SPL tokens from my account to some other. The transaction does work, as seen on solscan, but I get an error saying "Unable to confirm transaction xxxx"

I have skip_confirmation to False, maybe thats the issue?

**Comment by ZenRepublic** [comment]
transfer_checked seems to work better

**Comment by ZenRepublic** [comment]
Nope it doesn't.. Both transfer and transfer_checked always passes the transaction correctly, but throws an error most of the time...

**Comment by michaelhly** [comment]
Try using the `skip_confirmation` option:
https://michaelhly.github.io/solana-py/rpc/types/#solana.rpc.types.TxOpts.skip_confirmation
