### ISSUE TITLE
get_inflation_governor

### ISSUE THREAD

**Issue by lakejynch** [michaelhly/solana-py#28]
I've had some trouble when calling this RPC Method. Here's the error:

> AttributeError: 'Client' object has no attribute 'get_inflation_governor'

Although the version I pulled has this method in the Client class (lines 427-442):
`
def get_inflation_governor(self, commitment: Commitment = Max) -> RPCResponse:
        """Returns the current inflation governor.

        :param commitment: which bank state to query. It can be either "max", "root", "single" or "recent".

        >>> solana_client = Client("http://localhost:8899")
        >>> solana_client.get_inflation_governor() # doctest: +SKIP
        {'jsonrpc': '2.0',
         'result': {'foundation': 0.05,
          'foundationTerm': 7.0,
          'initial': 0.15,
          'taper': 0.15,
          'terminal': 0.015},
         'id': 5}
        """
        return self._provider.make_request(RPCMethod("getInflationGovernor"), {self._comm_key: commitment})
`
Not sure if this is on my end.

Also, the docs could use a slight edit. The section about the "get_inflation_rate()" method is a copy of the "get_inflation_governor()" above it:
![Capture](https://user-images.githubusercontent.com/56452947/92499246-a5c39400-f1c9-11ea-9d9a-daab4878b748.PNG)

**Comment by michaelhly** [comment]
@lakejynch can you check which version you pulled with `pip list`? Make sure you are on v0.1.1.

In my project here is what I get:
```
$ pip list
Package           Version  
----------------- ---------
base58            2.0.1    
certifi           2020.6.20
cffi              1.14.2   
chardet           3.0.4    
idna              2.10     
pip               19.0.3   
pycparser         2.20     
PyNaCl            1.4.0    
requests          2.24.0   
setuptools        40.8.0   
six               1.15.0   
solana            0.1.1     <--- Make sure you have this version
typing-extensions 3.7.4.3  
urllib3           1.25.10  
``` 

```python
>>> from solana.rpc.api import Client
>>> http_client = Client("https://devnet.solana.com")
>>> dir(http_client)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_comm_key', '_data_slice_key', '_encoding_key', '_provider', 'get_account_info', 'get_balance', 'get_block_commitment', 'get_block_time', 'get_cluster_nodes', 'get_confirmed_block', 'get_confirmed_blocks', 'get_confirmed_signature_for_address2', 'get_confirmed_transaction', 'get_epoch_info', 'get_epoch_schedule', 'get_fee_calculator_for_blockhash', 'get_fee_rate_governor', 'get_fees', 'get_first_available_block', 'get_genesis_hash', 'get_identity', '**get_inflation_governor**', 'get_inflation_rate', 'get_largest_accounts', 'get_leader_schedule', 'get_minimum_balance_for_rent_exemption', 'get_minimum_ledger_slot', 'get_program_accounts', 'get_recent_blockhash', 'get_signature_statuses', 'get_slot', 'get_slot_leader', 'get_stake_activation', 'get_supply', 'get_token_account_balance', 'get_token_accounts_by_delegate', 'get_token_accounts_by_owner', 'get_token_largest_accounts', 'get_token_supply', 'get_transaction_count', 'get_version', 'get_vote_accounts', 'is_connected', 'request_airdrop', 'send_raw_transaction', 'send_transaction', 'set_log_filter', 'simulate_transaction', 'validator_exit']
```

**Comment by lakejynch** [comment]
Re-installed 0.1.1, works now. Thanks for the help!
