### ISSUE TITLE
encoded intructions to hex

### ISSUE THREAD

**Issue by AKRD44** [michaelhly/solana-py#282]
This is not an issue specific to solana-py, I just didn't know where else to ask. 

I need to convert encoded instructions to hex. Does anyone know how to do that in Python?

H3DNhiDSYtdbL7SR2CxRW8y4TETGikzG9SXgPxM96FVh --> ee4c24da84b1e0e97f1edec80000000001000000000000004ba8f26200000000

Thanks!

**Comment by aleixisp** [comment]
If you have the instruction class 
You can just:

`ix_hex = instruction.__bytes__().hex()`

To reconstruct it to bytes:
`ix_bytes = bytes.fromhex(ix_hex)`

**Comment by kevinheavey** [comment]
Better to do `bytes(instruction).hex()` than `instruction.__bytes__().hex()` since magic methods aren't supposed to be called directly
