### ISSUE TITLE
Can't transfer tokens (ex. usdc) to another wallet

### ISSUE THREAD

**Issue by kusiev** [michaelhly/solana-py#284]
```
def send_spl_to_wallet(sender_privat_key, receiver_wallet, token_address, amount):
    sender_account_key = Keypair.from_secret_key(base58.b58decode(sender_privat_key))
    
    token_client = spl.token.client.Token(solana_client, PublicKey(token_address), TOKEN_PROGRAM_ID, sender_account_key)
    
    #* program_id - SPL-Token address; owner - SPL-Token account address; source - sender; dest - receiver;
    transaction = token_client.transfer(
        program_id = TOKEN_PROGRAM_ID,
        source=sender_account_key.public_key, # PK of token account you're transfering FROM
        dest=PublicKey(receiver_wallet), # PK of token account you're transfering TO
        owner=token_client.create_account(owner = sender_account_key.public_key), # Account that owns your source token account
        amount=int(amount*(10**9)),
        opts=TxOpts(skip_confirmation=False)
    )
    transaction_res = solana_client.send_transaction(transaction, sender_account_key)
    print(transaction_res)
```

**ERROR**:
solana.rpc.core.RPCException: {'code': -32002, 'message': 'Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.', 'data': {'accounts': None, 'err': 'AccountNotFound', 'logs': [], 'unitsConsumed': 0}}

**Comment by michaelhly** [comment]
Do you have SOL in the sender's wallet?

**Comment by kusiev** [comment]
> Do you have SOL in the sender's wallet?

~0.05 SOL

**Comment by kusiev** [comment]
**i did nothing with my code and now it's showing this error:**
solana.rpc.core.RPCException: {'code': -32002, 'message': 'Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1', 'data': {'accounts': None, 'err': {'InstructionError': [0, {'Custom': 1}]}, 'logs': ['Program 11111111111111111111111111111111 invoke [1]', 'Transfer: insufficient lamports 944280, need 2039280', 'Program 11111111111111111111111111111111 failed: custom program error: 0x1'], 'unitsConsumed': 0}}

**Comment by kusiev** [comment]
> You need to create a token account for the sender.

can you send me link to the docs please?

**Comment by michaelhly** [comment]
https://michaelhly.github.io/solana-py/spl/token/client/#spl.token.client.Token.create_account

**Comment by kusiev** [comment]
> https://michaelhly.github.io/solana-py/spl/token/client/#spl.token.client.Token.create_account

lol i literally dont understand whats wrong
`sender_account_key = Keypair.from_secret_key(base58.b58decode(sender_privat_key))
    
 token_client = spl.token.client.Token(solana_client, PublicKey(token_address), TOKEN_PROGRAM_ID, sender_account_key)
 account = token_client.create_account(sender_account_key.public_key)
 print(account)`

**Error**:
solana.rpc.core.RPCException: {'code': -32002, 'message': 'Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1', 'data': {'accounts': None, 'err': {'InstructionError': [0, {'Custom': 1}]}, 'logs': ['Program 11111111111111111111111111111111 invoke [1]', 'Transfer: insufficient lamports 944280, need 2039280', 'Program 11111111111111111111111111111111 failed: custom program error: 0x1'], 'unitsConsumed': 0}}

**Comment by kusiev** [comment]
> You need more SOL to pay for rent.

well, thank you firstly! but now a need to confirm transaction :) how can i do it?

`solana.rpc.core.UnconfirmedTxError: Unable to confirm transaction`

**Comment by kusiev** [comment]
> > You need more SOL to pay for rent.
> 
> well, thank you firstly! but now a need to confirm transaction :) how can i do it?
> 
> `solana.rpc.core.UnconfirmedTxError: Unable to confirm transaction`

NVM, i can create Token account, i pay fee and after fee its showing me this error:
**not enough signers**

I think something wrong in  token_client.transfer params
```
sender_account_key = Keypair.from_secret_key(base58.b58decode(sender_privat_key))

    token_client = spl.token.client.Token(solana_client, PublicKey(token_address), TOKEN_PROGRAM_ID, sender_account_key)
    token_account = token_client.create_account(PublicKey(receiver_wallet))
    print(token_account)
    #* program_id - SPL-Token address; owner - SPL-Token account address; source - sender; dest - receiver;
    transaction = token_client.transfer(
        #program_id = TOKEN_PROGRAM_ID,
        source = sender_account_key.public_key,
        dest = token_account,
        owner = PublicKey(receiver_wallet),
        amount = amount,
        opts = TxOpts(skip_confirmation=False)
    )
    transaction_res = solana_client.send_transaction(transaction, sender_account_key)
    print(transaction_res)
```

**Comment by michaelhly** [comment]
owner should be `sender_account_key.public_key` not `PublicKey(receiver_wallet)`

**Comment by kusiev** [comment]
> PublicKey(receiver_wallet),

just changed it. Getting same error

**Comment by kusiev** [comment]
if im changing `dest = token_account` to `dest = PublicKey(receiver_wallet)` i get `solana.rpc.core.UnconfirmedTxError: Unable to confirm transaction 2qUQciut3jL5zdDVes4biiL9efUJWSP2jMfvLHEDeD7R7wp2v8H2mJbR1pZHbtq8trJeSjq3bP2aSzVz62omJrnC`

**Comment by michaelhly** [comment]
This transaction worked: https://explorer.solana.com/tx/2qUQciut3jL5zdDVes4biiL9efUJWSP2jMfvLHEDeD7R7wp2v8H2mJbR1pZHbtq8trJeSjq3bP2aSzVz62omJrnC

Sometimes your RPC endpoint will have trouble confirming you can skip the tx confirmation with this option:
https://michaelhly.github.io/solana-py/rpc/types/#solana.rpc.types.TxOpts.skip_confirmation

**Comment by kusiev** [comment]
> This transaction worked: https://explorer.solana.com/tx/2qUQciut3jL5zdDVes4biiL9efUJWSP2jMfvLHEDeD7R7wp2v8H2mJbR1pZHbtq8trJeSjq3bP2aSzVz62omJrnC
> 
> Sometimes your RPC endpoint will have trouble confirming you can skip the tx confirmation with this option: https://michaelhly.github.io/solana-py/rpc/types/#solana.rpc.types.TxOpts.skip_confirmation

got it, fee is sending, tokens are sending, but after this it ends with error from send_transaction() function:

`transaction_res = solana_client.send_transaction(transaction, sender_account_key)`

**error**
```
transaction_res = solana_client.send_transaction(transaction, sender_account_key)
  File "C:\Users\*\AppData\Roaming\Python\Python310\site-packages\solana\rpc\api.py", line 1380, in send_transaction
    txn.recent_blockhash = recent_blockhash
AttributeError: 'dict' object has no attribute 'recent_blockhash'
```

**Comment by michaelhly** [comment]
When this happen every time or occasionally?
