### ISSUE TITLE
How to decode transaction instruction data

### ISSUE THREAD

**Issue by devlancer412** [michaelhly/solana-py#286]
I need to decode transaction instruction data.
For example instruction is like this:
```
[
  {
    "accounts": [
      2,
      3,
      1,
      0
    ],
    "data": "g7gn3dpVguJSb",
    "programIdIndex": 4
  }
]
```
And instruction data bs58 decode result is:
```
0c010000000000000000
```
And transaction instruction decode result is:
```
{
  "info": {
    "authority": "3mqxFEsLMsahLSTU7Xhmeb8Zi9LJnKc2QYtuzn3Lxts2",
    "destination": "A5cmqXq4fepJBSfpjNYtc4qJo5NrW4m6AW6BUY5dimDh",
    "mint": "CAvvk8RGWCGERB4CHBxh2FX2vXc8Qkj7soEqLKTnYgq2",
    "source": "Bvu5cd49cWq7vLAQQmtGYXHkCguimzyUWA73hjHokkAn",
    "tokenAmount": {
      "amount": "1",
      "decimals": 0,
      "uiAmount": 1,
      "uiAmountString": "1"
    }
  },
  "type": "transferChecked"
}
```

How to get this result? Please help me.

**Comment by crypt0miester** [comment]
reconstructing would require you to know the program instructions. the data for every program is different.

if this is really a transfer checked instruction then it is a system program ix, then you would be able to decode the data by deconstructing it using solana._layouts template. precisely the _TRANFER_LAYOUT.parse(data) function

**Comment by devlancer412** [comment]
> reconstructing would require you to know the program instructions. the data for every program is different.
> 
> if this is really a transfer checked instruction then it is a system program ix, then you would be able to decode the data by deconstructing it using solana._layouts template. precisely the _TRANFER_LAYOUT.parse(data) function

Thanks. It's works fine.
