### ISSUE TITLE
How to validate a SOL address?

### ISSUE THREAD

**Issue by yangbung** [michaelhly/solana-py#287]
I do this to validate ETH address:

```
from web3 import Web3
web3 = Web3()
is_address = web3.isAddress('Address')
```

Please help me on how I can validate a SOL address.

**Comment by michaelhly** [comment]
Validation is done in the contructor:
https://github.com/michaelhly/solana-py/blob/251403dbf5f528ce3870f9cb19dfaedcdee3ffb1/src/solana/publickey.py#L29
