### ISSUE TITLE
How to add third party fee payer?

### ISSUE THREAD

**Issue by hnguonly** [michaelhly/solana-py#289]
Hi @vcyleung @michaelhly,

I have similar code as below to transfer token. It works but I would like to have a third party fee payer, instead of paid by the "source". How would I do that?  Thanks!

------------

Heyo!

I am trying to send a custom SPL token I want to distribute to my holders. This is my code:

```python
from solana.publickey import PublicKey
from solana.account import Account
from solana.rpc.api import Client
from solana.transaction import Transaction
from solana.keypair import Keypair
from spl.token.instructions import transfer, TransferParams
from spl.token.constants import TOKEN_PROGRAM_ID

client = Client("https://api.mainnet-beta.solana.com")

secret_key= [...]
    
sender = Keypair.from_secret_key(bytes(secret_key))
receiver = PublicKey("BkoXyZy4Poam3E97Urd7rmwAvcyC3tZFBap1GHvFCjdS") # TOKEN Account

amount = int(10e6 * 5)

chick_coin = PublicKey("3RXTenk2bvx5cTYY8JrN94EFi3AkYCz9tzJzE7oRhSgf") # Mainnet address
chick_acc = PublicKey("6u4vEaj59irczDu17ydB6E9DTM4XVXZErTVe9LvFyNUG")

# https://michaelhly.github.io/solana-py/spl/intro/
transaction = Transaction().add(transfer(TransferParams(
    source=chick_acc, # PK of token account you're transfering FROM
    dest=receiver, # PK of token account you're transfering TO
    owner=sender.public_key, # Account that owns your source token account
    program_id = TOKEN_PROGRAM_ID,
    amount=amount
)))

res = client.send_transaction(transaction, sender)
```

Obtaining next result:
```
{
  'jsonrpc': '2.0',
  'result': '9cmfZ1zHkxwwUMzHdNAc15Ld2y5Y1PDbRpeuPhLcniPAEFRPTQrHW2akt3cpiYUX5Sgi2rSgTVz3zQPk99jaf2h',
  'id': 2
}
```

But the tokens sometimes are transferred, most of the time no, and never got a bad/error result from the res...

Can you help me? @vcyleung @michaelhly

_Originally posted by @MarioProjects in https://github.com/michaelhly/solana-py/issues/60#issuecomment-1054435716_

**Comment by hnguonly** [comment]
Update on my post...

It appears that by adding one more "fee_payer" parameter to the "send_transaction" method I was able to direct payment's responsibility to this payer.  The order of its appearance in the parameter list is important here, the intended payer must appear first in the parameter list as shown below. So far it works, I hope it's not just by accident. If someone can confirm or explain the behavior here, it's greatly appreciated.

res = client.send_transaction (transaction, **fee_payer**, sender)

**Comment by michaelhly** [comment]
Related https://github.com/michaelhly/solana-py/issues/268

**Comment by hnguonly** [comment]
Refer to #268 for detail discussion

**Comment by hnguonly** [comment]
Thanks ev
