### ISSUE TITLE
To run this project make sure you upgrade your python version

### ISSUE THREAD

**Issue by cyriimm** [michaelhly/solana-py#29]
Just writing for helping anyone experiencing installation issues or using python version lower than 3.7
This project will not be able to install the dependencies needed if you are using python version lower than 3.7
I just upgraded to latest python version 3.8.5 and it installs the dependencies and everything runs fine :)

**Comment by michaelhly** [comment]
Yes. Sorry about this. I will update the docs and README.

**Comment by michaelhly** [comment]
This should be fixed in v0.2.0.
