### ISSUE TITLE
Issue with the installation of the package

### ISSUE THREAD

**Issue by kaushikc44** [michaelhly/solana-py#290]
Hi so I have tried installing the package multiple times, Even tho it says the requirements are fulfilled. It denies the package upon importing. 

<WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
> 
And these are the warning as well thrown .

**Comment by michaelhly** [comment]
Can you provide more info?

**Comment by kaushikc44** [comment]
What all information do you need ? I would send those details here.

**Comment by kevinheavey** [comment]
I have no idea what you're saying but perhaps try upgrading pip

**Comment by kevinheavey** [comment]
Do you have a file in your project called solana.py perhaps?

**Comment by kaushikc44** [comment]
Ya , I did have a file named solana.py Really sorry to distrub you all. Is there any contribution I can make in order to help the community of Solana py grow ?

**Comment by kevinheavey** [comment]
No worries! A great thing to do would be find something in the Solana Cookbook that has a TypeScript example but not a Python example, and add a Python example to it https://solanacookbook.com/#contributing

**Comment by kaushikc44** [comment]
Thanks alot... Closing the thread
