### ISSUE TITLE
Can't send token PLZ Help

### ISSUE THREAD

**Issue by thdwoqor** [michaelhly/solana-py#292]
```
SOLANA_CLIENT = Client("https://api.mainnet-beta.solana.com")
WALLET=
WALLET2=
IP3_mint = PublicKey("3uejHm24sWmniGA5m4j4S1DVuGqzYBR5DJpevND4mivq")
token_client = Token(SOLANA_CLIENT, IP3_mint, TOKEN_PROGRAM_ID, WALLET)

transaction = token_client.transfer(
    source = WALLET.public_key,
    dest = PublicKey(''),
    owner = WALLET,
    amount = int(10e8 * 0.01),
    opts = TxOpts(skip_confirmation=True)
)

response = SOLANA_CLIENT.send_transaction(transaction,WALLET.public_key,WALLET)
```

https://solscan.io/token/3uejHm24sWmniGA5m4j4S1DVuGqzYBR5DJpevND4mivq

I've been up all night to send this token but I failed someone help me

**Comment by michaelhly** [comment]
Did you create a token account for the receiver ?

**Comment by thdwoqor** [comment]
> 수신자를 위한 토큰 계정을 만드셨습니까?

`token_account = IP3_token_client.create_account(WALLET.public_key)`

I made it like this and put it in 'owner', 'dest', 'source', but it failed.

**Comment by thdwoqor** [comment]
i need a good example

**Comment by thdwoqor** [comment]
> Did you create a token account for the receiver ?


i need a good example

**Comment by michaelhly** [comment]
https://github.com/michaelhly/solana-py/blob/bf8f93e02392270571e07d060ede7a1e69ffc33a/tests/integration/test_token_client.py#L145

**Comment by thdwoqor** [comment]
> https://github.com/michaelhly/solana-py/blob/bf8f93e02392270571e07d060ede7a1e69ffc33a/tests/integration/test_token_client.py#L145

`
WALLET=
WALLET2=
SOLANA_CLIENT = Client("https://api.mainnet-beta.solana.com")

IP3_mint = PublicKey("3uejHm24sWmniGA5m4j4S1DVuGqzYBR5DJpevND4mivq")  # Mainnet address



token_client = Token(SOLANA_CLIENT, IP3_mint, TOKEN_PROGRAM_ID, WALLET)
token_sender = token_client.create_account(owner =WALLET.public_key)
token_receiver = token_client.create_account(owner =WALLET2.public_key)

transaction = token_client.transfer(
    source = token_sender,
    dest = token_receiver,
    owner = WALLET,
    amount = int(10e8 * 0.01),
    opts = TxOpts(skip_confirmation=False)
)

response = SOLANA_CLIENT.send_transaction(transaction, WALLET)

print(response)`

Still Fail ,
What the hell am I doing wrong?
https://solscan.io/account/8bPskkaySzy7qHeWMjTYxKCEAfQtdRaNtW2G6yob9uJg
Only the fee from 'CreateAccount' is coming out

**Comment by thdwoqor** [comment]
> https://github.com/michaelhly/solana-py/blob/bf8f93e02392270571e07d060ede7a1e69ffc33a/tests/integration/test_token_client.py#L145

solved it thank you
