### ISSUE TITLE
Exceeded maximum number of instructions allowed 

### ISSUE THREAD

**Issue by alebuffoli** [michaelhly/solana-py#293]
Hello, I'am getting the following error while I try to mint an NFT

`Program failed to complete: exceeded maximum number of instructions allowed (342) at instruction #9413`

To solve this issue in javascript I would do something similar to this:

```
const additionalComputeBudgetInstruction =
    anchor.web3.ComputeBudgetProgram.requestUnits({
      units: 800000,
      additionalFee: 0,
    });

let method = await program.methods.someMethod(
    {
    accounts: {
      ...
    },
    signers: [...],
    preInstructions: additionalComputeBudgetInstruction
});
```

I've searched it in the SolanaPy docs, but I couldn't find anything related to this.

How can I require more units with the SolanaPy code?
Thankyou.

**Comment by michaelhly** [comment]
We need to add the equivalent instruction bindings.

**Comment by crypt0miester** [comment]
you are using anchor in js but using solana python? maybe try using anchor py?

the error shown is basically the number of instructions are 342 rather than a compute units issue. please include more of the your python code. perhaps there is something wrong there.

**Comment by kevinheavey** [comment]
Closing because solders covers this https://kevinheavey.github.io/solders/api_reference/compute_budget.html
