### ISSUE TITLE
Is master branch stable enough to use instead of waiting for releases?

### ISSUE THREAD

**Issue by SpaceMonkeyForever** [michaelhly/solana-py#300]
The current stable release, 0.25.1, depends on solders < 0.3.0 which is too old. I want to use the latest solders or at least a more recent one.

I can see `master` depends on 0.5.1

Is it wise to use `master` branch in production?

**Comment by kevinheavey** [comment]
Stuff has to pass CI tests to get merged to master so that makes it reasonably safe. The main risk is that the library would be inconsistent in some way because of some changes happening over multiple PRs.
