### ISSUE TITLE
Is this library production ready?

### ISSUE THREAD

**Issue by marciobbj** [michaelhly/solana-py#303]
Hi, I would like to know more about the development of this lib. I am very interested in having the Solana JS lib ported to Python, and I would be glad to start contributing to the library development. Can you give me directions on where to start if I want to get involved with the project? 

Thanks!

**Comment by kevinheavey** [comment]
Yeah it's production-ready and lots of people are using it in prod. One good place to help would be to identify RPC methods from [here](https://docs.solana.com/developing/clients/jsonrpc-api) that are missing from solana-py and open issues/PRs for them

**Comment by marciobbj** [comment]
Cool, I will work on the endpoints as I need them for my project.
