### ISSUE TITLE
Is there a way to get the token metadata info?

### ISSUE THREAD

**Issue by marciobbj** [michaelhly/solana-py#306]
I am starting a project recently and I was using node-js until I found out about this library. In the metaplex library I have been using (JS) I have the NFT model that is described as follows https://github.com/metaplex-foundation/js#the-nft-model - my question is: Is there a way to get all this info such as URI, collection details, symbol etc by just using these methods provided by Solana-py, or the Metaplex team worked in a more advanced way to provide access to this information?

**Comment by kevinheavey** [comment]
There's a Python API for Metaplex but I've never tried it: https://github.com/metaplex-foundation/python-api

Either way it's probably out of scope for solana-py
