### ISSUE TITLE
VersionedTransaction support for `send_transaction` method

### ISSUE THREAD

**Issue by enzoampil** [michaelhly/solana-py#320]
Currently, the `send_transaction` [method](https://github.com/michaelhly/solana-py/blob/55b91a9522b7c459e1fe67118c24efee0ffccc7e/src/solana/rpc/async_api.py#L999) only supports legacy transactions.

We'll need to support an updated method similar to the typescript `sendTransaction` [method](https://github.com/solana-labs/solana-web3.js/blob/ed1fe6d996902e4f43318d9e053f84d4b15f58f6/src/connection.ts#L4941) which supports solders [VersionedTransaction](https://github.com/kevinheavey/solders/blob/c5a1dd140704bd32d6be448161c979f2d9d826e0/python/solders/transaction.pyi#L96)

**Comment by iskeceli** [comment]
How can I use versionedtransaction operations from python_?

**Comment by kevinheavey** [comment]
Closed by #334

**Comment by ProximaCA** [comment]
so how??
