### ISSUE TITLE
No integration test for using WS program_subscribe with a filter

### ISSUE THREAD

**Issue by eliotstock** [michaelhly/solana-py#321]
I'd really like to know how to use a filter based on `offset` and `bytes` in a call to `program_subscribe`. Do you think you could add an integration test for this? `program_subscribe` has only one test so far.

**Comment by kevinheavey** [comment]
I don't think we need an integration test for this but documentation would be good. We do have examples for [get_program_accounts](https://michaelhly.github.io/solana-py/rpc/api/#solana.rpc.api.Client.get_program_accounts) though. The filters work the same for get_program_accounts and program_subscribe
