### ISSUE TITLE
solders.pubkey.Pubkey needs always be transformed into solana.pubkey.Pubkey

### ISSUE THREAD

**Issue by jmvsrules** [michaelhly/solana-py#326]
I was trying to transfer SPL tokens over solana.py I achieved this by fetching the corresponding SPL token and the associated token accounts of the 2 wallets (sender and receiver).
When I wanted to send this though, I always hit the error 
> AttributeError: 'solders.pubkey.Pubkey' object has no attribute 'to_solders'

This was because the Pubkeys of the associated token accounts were objects from the class 
> solders.pubkey.Pubkey

Instead, for being able to use them, I needed to turn the solder.pubkey.Pubkey into a
> solana.pubkey.Pubkey

class to be able to manage a transfer.

Might it be able to either write it somewhere (maybe I just did not find it as well) or make it into the code that .to_solders only is being used when it is a solana.pubkey.Pubkey or something. I tried to solve it for 2 days with this quite trivial error.

Thank you and have a great day!
JMV

**Comment by kevinheavey** [comment]
Maybe we should just remove `solana.public_key` entirely and use `solders.pubkey` everywhere. Thoughts @michaelhly ?

**Comment by michaelhly** [comment]
Sure! Fine with me!

**Comment by kevinheavey** [comment]
Closed by #329
