### ISSUE TITLE
Function get_program_accounts broken (Solders incompatibility)

### ISSUE THREAD

**Issue by AnderUstarroz** [michaelhly/solana-py#327]
The following example[ from docs](https://michaelhly.github.io/solana-py/rpc/api/#solana.rpc.api.Client.get_program_accounts) seems to be broken:
```
>>> from solana.rpc.types import MemcmpOpts
>>> solana_client = Client("http://localhost:8899")
>>> memcmp_opts = [
...     MemcmpOpts(offset=4, bytes="3Mc6vR"),
... ]
>>> pubkey = PublicKey("4Nd1mBQtrMJVYVfKf2PJy9NZUZdTAsp7D4xWLs4gDB4T")
>>> filters = [17, memcmp_opts]
>>> solana_client.get_program_accounts(pubkey, filters=filters).value[0].account.lamports
```

Throws:
```
    solana_client.get_program_accounts(pubkey, filters=filters)
  File "/usr/local/lib/python3.9/site-packages/solana/rpc/api.py", line 632, in get_program_accounts
    body = self._get_program_accounts_body(
  File "/usr/local/lib/python3.9/site-packages/solana/rpc/core.py", line 308, in _get_program_accounts_body
    None if filters is None else [x if isinstance(x, int) else Memcmp(*x) for x in filters]
  File "/usr/local/lib/python3.9/site-packages/solana/rpc/core.py", line 308, in <listcomp>
    None if filters is None else [x if isinstance(x, int) else Memcmp(*x) for x in filters]
TypeError: Memcmp.__new__() missing 1 required positional argument: 'bytes_'
```

Tested on:
 - Python v3.9.9
 - solana v0.27.2

**Comment by AnderUstarroz** [comment]
Seems like it comes from an inconsistency between this library and solders, but I don't know if the right solution should be either renaming `bytes_`to `bytes` in [the  Solders filter](https://github.com/kevinheavey/solders/blob/81a1ef19168f5a16884a2c88dc7d476b2cdb58ba/src/rpc/filter.rs#L72) or update [your type.py file](https://github.com/michaelhly/solana-py/blob/3a43bf71ad2a7d281d2b428daa104635ec8f4ed8/src/solana/rpc/types.py#L35) the other way around to match solders.

**Comment by AnderUstarroz** [comment]
@kevinheavey  sorry to call you in Dubliner :) but I guess you would know what needs to be done here.

**Comment by kevinheavey** [comment]
@AnderUstarroz I think your second issue is just because you have a solders Pubkey there, not a `solana.public_key.PublicKey`

**Comment by AnderUstarroz** [comment]
But shouldn't `solana_client.get_program_accounts(PROGRAM_ID)` return instances of pubkeys with their corresponding  `.to_solders()`method without having to cast it using `PublicKey(account.pubkey)`? 

Thanks @kevinheavey

**Comment by kevinheavey** [comment]
I think we'll just get rid of `solana.publickey.PublicKey` soon as it doesn't provide any benefit over `solders.pubkey.Pubkey`
