### ISSUE TITLE
Add transfer with seed 

### ISSUE THREAD

**Issue by Dassy23** [michaelhly/solana-py#330]
Would be great to have the transfer with seeds functionality available. Avail in the solders lib below.
https://github.com/kevinheavey/solders/blob/main/python/solders/system_program.py#L268

**Comment by kevinheavey** [comment]
@Dassy23 if anything we'll probably delete system_program.py and point people to Solders. Now that we've removed solana-py's `Instruction`, `PublicKey` and `AccountMeta` classes, system_program.py is basically doing nothing that solders doesn't do

**Comment by Dassy23** [comment]
Ya thats a good idea, Im just using soldiers for most cases. Its a nice and easy codebase
