### ISSUE TITLE
Make SPL library more pythonic

### ISSUE THREAD

**Issue by michaelhly** [michaelhly/solana-py#344]
- [ ] wrap keyword argument interfaces over [NamedTuple](https://github.com/michaelhly/solana-py/search?q=namedtuple) classes

**Comment by azerv1** [comment]
would you like them to be a @staticmethod in each class or separate functions with the same name outside the class? 
`class ClusterUrls(NamedTuple):
    """A collection of urls for each cluster."""

    devnet: str
    testnet: str
    mainnet_beta: str

def cluster_urls(*, devnet:str , testnet:str, mainnet_beta: str) -> ClusterUrls:
    """ClusterUrls wrapper."""
    return ClusterUrls(devnet=devnet,testnet=testnet,mainnet_beta=mainnet_beta)` like this?

**Comment by michaelhly** [comment]
After introducing of solders, I think this only applies to the SPL library now.

We should make the construction of SPL instructions more pythonic by making them constructible with dictionaries: 
- https://github.com/michaelhly/solana-py/blob/2afacbd0ad2a7ef57154cd16a6f1034694afb0f9/src/spl/memo/instructions.py#L11
- https://github.com/michaelhly/solana-py/blob/2afacbd0ad2a7ef57154cd16a6f1034694afb0f9/src/spl/token/instructions.py#L16
