### ISSUE TITLE
Pubkey elaboration

### ISSUE THREAD

**Issue by Sentientech** [michaelhly/solana-py#349]
Due to my inexperience, I did not know I had to convert the wallet address to base58 before passing it into the Pubkey() function.
Only found out after watching this video I just happened to stumble upon: [public keys](https://www.youtube.com/watch?v=mKJKIgTJ6LY&list=TLPQMDEwNTIwMjP4209NVE8gGw&index=3)
Notice to everyone:

**When using this library, make sure to use it as follows:**

```
from solana.rpc.api import Client
from solders.pubkey import Pubkey
from base58 import b58decode

solana_client = Client("https://api.mainnet-beta.solana.com") /[devnet](https://api.devnet.solana.com), [testnet](https://api.testnet.solana.com)
public_key = b58decode(<wallet_address>)
print(solana_client.get_balance(Pubkey(public_key1)).value)
```

**Comment by michaelhly** [comment]
Use `str(public_key)`:
https://kevinheavey.github.io/solders/api_reference/pubkey.html#solders.pubkey.Pubkey

**Comment by Sentientech** [comment]
Thank you
