### ISSUE TITLE
Can't append to Instruction Accounts

### ISSUE THREAD

**Issue by Bewinxed** [michaelhly/solana-py#353]
In the previous versions, I used to be able to create a **TransferChecked** instruction and then append an account to it, for SolanaPay, I need to add a reference account (pubkey) to the list of accounts in the tx.

However, appending to the instruction.accounts now does nothing, the list stays the same.

assigning to the list like instruction.accounts = instruction.accounts + [AccountMeta(reference, False, False)] appends the list but the instruction still doesn't include that account in the list.

How to go about that? I'm just making a transaction checked but i need to include the account in the transaction somehow.

Thanks!

**Comment by michaelhly** [comment]
@Bewinxed could you provide a code snippet?

**Comment by Bewinxed** [comment]
```python
transactionAmount = int(
                (
                    amount * LAMPORTS_PER_SOL * Decimal(1 - feePercentage)
                ).to_integral_value("ROUND_FLOOR")
            )
            transactionInstruction = transfer(
                TransferParams(from_pubkey=payer, to_pubkey= recipient, lamports= transactionAmount)
            )
            feeAmount = int(
                (
                    amount * LAMPORTS_PER_SOL * Decimal(feePercentage)
                ).to_integral_value("ROUND_FLOOR")
            )
            feeInstruction = transfer(
                TransferParams(from_pubkey=payer, to_pubkey= feeRecipient, lamports= feeAmount)
            )
            **transactionInstruction.accounts = transactionInstruction.accounts + [
                AccountMeta(reference, False, False)
            ]** <-- this used to work
            transaction.add(transactionInstruction, feeInstruction)
            ```

**Comment by michaelhly** [comment]
it got moved over here:
https://kevinheavey.github.io/solders/api_reference/instruction.html#solders.instruction.Instruction

**Comment by Bewinxed** [comment]
So we can't use transfer checked and add to the result of it? Gotta build
it manually?

**Comment by michaelhly** [comment]
cc @kevinheavey, is there a method in solders where we can append to account meta? If not where would be an appropriate place to add one?

**Comment by kevinheavey** [comment]
I'd recommend just building it manually. We could add mutability to the solders Instruction but that would introduce a major footgun: https://pyo3.rs/main/faq#pyo3get-clones-my-field

Safer to have one grug-brained way to do it imo

**Comment by Bewinxed** [comment]
So how would I build a transfer_checked transaction using this?

Trying to wrap my head around the new changes.

Thanks!

**Comment by kevinheavey** [comment]
Something like this:
```python
LAMPORTS_PER_SOL = Decimal("1000000000")


transactionAmount = int(
                (
                    amount * LAMPORTS_PER_SOL * Decimal(1 - feePercentage)
                ).to_integral_value("ROUND_FLOOR")
            )
base_ix = transfer(
                TransferParams(from_pubkey=payer, to_pubkey= recipient, lamports= transactionAmount)
            )
feeAmount = int(
                (
                    amount * LAMPORTS_PER_SOL * Decimal(feePercentage)
                ).to_integral_value("ROUND_FLOOR")
            )
feeInstruction = transfer(
                TransferParams(from_pubkey=payer, to_pubkey= feeRecipient, lamports= feeAmount)
            )
transaction_instruction = Instruction(base_ix.program_id, base_ix.data, base_ix.accounts  + [AccountMeta(reference, False, False)])
```

**Comment by Bewinxed** [comment]
Works great, thank you!

**Comment by kevinheavey** [comment]
@Bewinxed I forgot that solders actually is supposed to support overwriting the accounts field.

It even has a passing test for this behaviour:
```
@fixture
def ix() -> Instruction:
    return Instruction(
        Pubkey.default(), b"1", [AccountMeta(Pubkey.new_unique(), True, True)]
    )

@fixture
def am() -> AccountMeta:
    return AccountMeta(Pubkey.new_unique(), True, True)

def test_accounts_setter(ix: Instruction, am: AccountMeta) -> None:
    new_accounts = [am]
    ix.accounts = new_accounts
    assert ix.accounts == new_accounts
```

What behaviour exactly are you seeing here?
> assigning to the list like instruction.accounts = instruction.accounts + [AccountMeta(reference, False, False)] appends the list but the instruction still doesn't include that account in the list.

**Comment by Bewinxed** [comment]
If you do tx.accounts.append(account), then account doesn't get appended to
the list at all.

if you do tx.accounts = tx.accounts + [account] the list gets appended,
however if you try to send the transaction, that account isn't included at
all in the transaction.
