### ISSUE TITLE
Help with versionedtransactions

### ISSUE THREAD

**Issue by RiadZX** [michaelhly/solana-py#361]
Hi, I use the magiceden API to get instructions to buy/list nfts on their marketplace. They added a versionedtransaction option, I however could not figure out how to do it using solana-py. Any examples on how to send versionedtransactions would be appreciated.

Thanks in advance

**Comment by michaelhly** [comment]
Use this here:
https://kevinheavey.github.io/solders/api_reference/transaction.html#solders.transaction.VersionedTransaction

and use the `solana-py` client to broadcast the transaction

**Comment by RiadZX** [comment]
Thanks, I created a transaction but how can I send it? couldnt find anything in solders
