### ISSUE TITLE
Question: Transaction confirmation timeout

### ISSUE THREAD

**Issue by sdevkc** [michaelhly/solana-py#380]
Is there any reason why the default timeout is 30 seconds in `confirm_transaction`? Although it is impossible to predict the timeout, but wouldn't it make more sense to use 60 - 90 seconds?

https://docs.solana.com/developing/transaction_confirmation#how-does-transaction-expiration-work

**Comment by michaelhly** [comment]
@sdevkc would you mind creating a PR to change it for us? 🙏
