### ISSUE TITLE
Bump cachetools

### ISSUE THREAD

**Issue by jackwardell** [michaelhly/solana-py#395]
Any chance we could bump cachetools? or at least change to >=4.2.2 instead of ^4.2.2? 

4.2.2 is nearly 3 years old now and is causing irreconcilable conflicts for me https://github.com/tkem/cachetools/blob/master/CHANGELOG.rst

Happy to help or put in a PR if you're open to it

**Comment by michaelhly** [comment]
@jackwardell happy to accept a PR

**Comment by michaelhly** [comment]
Actually cache tools got removed in https://github.com/michaelhly/solana-py/commit/7d41f635367e8dde5116e6d776fbb714a1b36d29
