### ISSUE TITLE
Module Not Found Error

### ISSUE THREAD

**Issue by BnThSurv** [michaelhly/solana-py#411]
Howdy,

I am receiving this error when running my code:

Traceback (most recent call last):
  File "C:\Users\bean\OneDrive\Desktop\SolWal3.py", line 75, in <module>
    from solana.account import Account
ModuleNotFoundError: No module named 'solana.account'

Any suggestions on how to get passed this issue? I've tried updating pip and installing solana-py from the source code. I've also tried searching for the sub-module in the library, has the structure changed?

cheers!

**Comment by michaelhly** [comment]
Yes. Please use https://kevinheavey.github.io/solders/

**Comment by BnThSurv** [comment]
Awesome, thankyou.

**Comment by ujsyehao** [comment]
how to use it, 
solders not have account

**Comment by michaelhly** [comment]
> kevinheavey.github.io/solders

It does: https://kevinheavey.github.io/solders/api_reference/account.html
