### ISSUE TITLE
ModuleNotFoundError: No module named 'solana.publickey'

### ISSUE THREAD

**Issue by xiaohuangwritebug** [michaelhly/solana-py#414]
code ：from solana.publickey import PublicKey

----------------------------------------------------
>>>ModuleNotFoundError: No module named 'solana.publickey'

**Comment by xiaohuangwritebug** [comment]
I have tried reinstalling the env

**Comment by kevinheavey** [comment]
This module hasn't existed for almost two years. Are there out of date docs somewhere that told you to use it?

What you want is in Solders https://kevinheavey.github.io/solders/tutorials/pubkeys.html
