### ISSUE TITLE
get_associated_token_address works for mainnet only

### ISSUE THREAD

**Issue by tomasjur** [michaelhly/solana-py#415]
Hi,
[get_associated_token_address](https://github.com/michaelhly/solana-py/blob/4237ff2a56a7bf29fa98c7bdb595237300c24dff/src/spl/token/instructions.py#L1214) in /spl/token/instructions.py works well, but gets an associated address which is in mainnet. It's kind of okay, but I need a devnet wallet address while developing.

Anyway, I could specify the endpoint? I have a workaround for this, but using this function as others with/from the AsyncClient or AsyncToken would help to minimize the code.

Thanks!

**Comment by michaelhly** [comment]
You set the endpoint when you initialize the client:
https://github.com/michaelhly/solana-py#api-client
