### ISSUE TITLE
Adding proxies

### ISSUE THREAD

**Issue by monkeyden** [michaelhly/solana-py#424]
I'm going to take a stab at adding proxy support.  Is it safe to start with master or should I use [v0.34.0](https://github.com/michaelhly/solana-py/tree/v0.34.0)?

**Comment by michaelhly** [comment]
Master is safe!

**Comment by michaelhly** [comment]
Oh. Like fallback endpoints?

**Comment by michaelhly** [comment]
I'm do not think that should be added into this library. Perhaps you can start your own package and wrap the `Client` or `AsyncClient. 

cc @kevinheavey

**Comment by kevinheavey** [comment]
Yeah agreed with @michaelhly. But do let us know if something about solana-py's design makes it unnecessarily difficult to add proxy support in a new library

**Comment by Jonney** [comment]
I believe it is very necessary to add the feature of using a proxy because there are firewalls in this world, and using a proxy can bypass them.

What we need to do is add an argument in the __init__() and pass it to the httpx.Client(), very simple. I can make a PR if this modification is allowed.

**Comment by michaelhly** [comment]
> I believe it is very necessary to add the feature of using a proxy because there are firewalls in this world, and using a proxy can bypass them.
> 
> What we need to do is add an argument in the **init**() and pass it to the httpx.Client(), very simple. I can make a PR if this modification is allowed.

Feel free! I can include it in the next release!

**Comment by Jonney** [comment]
Here you go.
https://github.com/michaelhly/solana-py/pull/479
@michaelhly

**Comment by michaelhly** [comment]
@Jonney Released in `v0.36.1`

🎉
