### ISSUE TITLE
enhance type hinting for 'connect' to improve IDE support and dev experience

### ISSUE THREAD

**Issue by circansm** [michaelhly/solana-py#434]
**Problem:**
When using `connect` as demonstrated in the official documentation, IDEs like PyCharm or VSCode incorrectly interpret the type of the returned object as `WebSocketClientProtocol` instead of `SolanaWsClientProtocol`. This leads to a lack of autocompletion and type checking for methods like `logs_subscribe`, which are specific to `SolanaWsClientProtocol`.

**Steps to Reproduce:**
1. Use the `connect` method in an async context as per the example in the documentation.
2. Try to call `logs_subscribe` on the returned object.
3. Notice that IDEs do not offer autocompletion for `logs_subscribe` and may show a type warning.

**Expected Behavior:**
The `connect` method should be clearly typed to return `SolanaWsClientProtocol`, allowing IDEs to correctly infer the available methods and properties.

**Possible Solution:**
Enhance the type annotations in the `connect` function to explicitly indicate that it returns an instance of `SolanaWsClientProtocol`. This could involve adjusting the function's docstring and annotations to provide more explicit guidance to both developers and tools like IDEs.

**Additional Context:**
- Solana-py version: 0.34.0
- Python version: 3.12
- Operating System: Windows
- IDE: Visual Studio Code

**Comment by michaelhly** [comment]
Happy to accept a PR!

**Comment by michaelhly** [comment]
Completed by #437
