### ISSUE TITLE
bump websockets to 12.0

### ISSUE THREAD

**Issue by benjiqq** [michaelhly/solana-py#445]
websockets 12.0 has been published for a while

```solana (0.34.2) depends on websockets (>=9.0,<12.0), solana (>=0.34.2,<0.35.0) requires websockets (>=9.0,<12.0).```

**Comment by michaelhly** [comment]
happy to accept a PR!

**Comment by azerv1** [comment]
Hello, on my fork I tried to update websockets to 12.0 with poetry and all the tests are still passing, what am I am missing?

**Comment by michaelhly** [comment]
Would you mind re-opening this PR?
https://github.com/michaelhly/solana-py/pull/464

We just have to make sure none of the integration tests break.
