### ISSUE TITLE
Support websocket connections

### ISSUE THREAD

**Issue by michaelhly** [michaelhly/solana-py#45]
Add websocket client for https://docs.solana.com/apps/jsonrpc-api#subscription-websocket

**Comment by dsaccon** [comment]
No takers for this yet?

**Comment by datgrog** [comment]
That would be nice

**Comment by quazzuk** [comment]
is this functionality currently being worked on?

**Comment by kevinheavey** [comment]
yes I'm working on it this week! Was busy with anchorpy stuff

**Comment by quazzuk** [comment]
Great news! I actually ended up here after finding this https://github.com/serum-community/pyserum/issues/78
