### ISSUE TITLE
Update ruff Dependency to Latest Version

### ISSUE THREAD

**Issue by HaranK007** [michaelhly/solana-py#452]
Hi, I noticed that the current ruff version in the project is set to ruff = "^0.0.219", which is quite outdated. Could you please consider updating it to use the latest version?

It might also be helpful to set the version requirement as ruff = "*" to automatically track the latest stable version.

**Comment by kevinheavey** [comment]
> It might also be helpful to set the version requirement as ruff = "*" to automatically track the latest stable version.

Let's not do this part
