### ISSUE TITLE
Keypair Module Issue

### ISSUE THREAD

**Issue by P9428** [michaelhly/solana-py#454]
I'm attempting to build a Solana trading bot using Python and the solana-py library. However, after installing solana-py, I'm encountering an error when trying to import the Keypair module. It seems like the package doesn't contain a keypair module. Any someone help me with this?

**Comment by michaelhly** [comment]
Please use the keypair module from https://kevinheavey.github.io/solders/api_reference/keypair.html

**Comment by P9428** [comment]
Got it thanks!
