### ISSUE TITLE
rpc.api.send_transaction() - change "transfer" to "Transaction.add(transfer"

### ISSUE THREAD

**Issue by kozhevnykov** [michaelhly/solana-py#46]
rpc.api.send_transaction()
line 954:
transfer --> TransactionInstruction, but tx should be Transaction object. 

just change comment section, to provide correct example. 

tx = Transaction.add(transfer(TransferParams(
        ...     from_pubkey=sender.public_key(), to_pubkey=reciever.public_key(), lamports=1000)))

**Comment by michaelhly** [comment]
Fixed. Thank you!
