### ISSUE TITLE
64 bytes private key for Account 

### ISSUE THREAD

**Issue by yurenji** [michaelhly/solana-py#47]
I am initing my account object as follows
```
private_key = bytes([89,136,139,8,93,189,44,2, ...... , 122,168])
payer = Account(private_key) 
```
but got the following error: 
```
  File "/Users/yurenji/.pyenv/versions/yurenji3.8/lib/python3.8/site-packages/solana/account.py", line 29, in __init__
    self._secret = public.PrivateKey(key) if key else public.PrivateKey.generate()
  File "/Users/yurenji/.pyenv/versions/yurenji3.8/lib/python3.8/site-packages/nacl/public.py", line 89, in __init__
    raise exc.TypeError(("PrivateKey must be created from a {0} "
nacl.exceptions.TypeError: PrivateKey must be created from a 32 bytes long raw secret key
```

It seems the private key must be 32 bytes. My account is created with solfare.com, and the private key it generates is 64 bytes. 

I wonder is there any plan to support 64 bytes private key?

**Comment by michaelhly** [comment]
@yurenji Hey. You just need to slice your 64 bytes private key in half. And pass in the second half to `Account`.

**Comment by BejanSadeghian** [comment]
Isn't it the _first half_ not second half of the 64 byte private key?
