### ISSUE TITLE
Any reason to not use httpx.Client and directly use httpx.post?

### ISSUE THREAD

**Issue by neochine** [michaelhly/solana-py#474]
https://github.com/SuperteamDAO/solathon/blob/master/solathon/core/http.py#L28
A similar library uses httpx.Client which is generally faster than httpx.post. This will also help adding proxy easily: https://github.com/michaelhly/solana-py/issues/424 since you need to pass proxy to Client()
```
import time
import httpx

# Benchmark with httpx.Client()
start = time.time()
with httpx.Client() as client:
    for _ in range(10):
        client.get("https://google.com")
end = time.time()
print(f"With httpx.Client(): {end - start} seconds")

# Benchmark with httpx.get()
start = time.time()
for _ in range(10):
    httpx.get("https://google.com")
end = time.time()
print(f"With httpx.get(): {end - start} seconds")
```
httpx.Client is generally faster

**Comment by michaelhly** [comment]
Happy to accept a PR!
