### ISSUE TITLE
How to get a list of all tokens from SOL address?

### ISSUE THREAD

**Issue by chiwalfrm** [michaelhly/solana-py#48]
The API has a method to get SPL token balance, but you have to know the token address ahead of time.

Question: Is there an API method to get a list of ALL tokens for a specific SOL address?

**Comment by michaelhly** [comment]
Sorry for the late reply. Here they are:
https://github.com/project-serum/serum-ts/blob/master/packages/tokens/src/mainnet-beta.json

**Comment by chiwalfrm** [comment]
that's cool but do you think you would implement a method in your solana-py client?  Something like get_list_of_tokens() like you already have get_token_account_balance() ?

**Comment by chiwalfrm** [comment]
are you saying that you are supposed to check every MintAddress for a balance?  this could get out-of-control when there are hundreds of thousands of SPL tokens

**Comment by michaelhly** [comment]
Sorry, not that I know of, at least no easy way. You have to look up a mint address you know.

It's kind of hard to do this on Solana since all state is stored in an [account](https://docs.solana.com/developing/programming-model/accounts).

**Comment by chiwalfrm** [comment]
closing this issue because Tyera at the Solana discord gave the answer: https://docs.solana.com/developing/clients/jsonrpc-api#gettokenaccountsbyowner

set programId = TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA and it works

**Comment by chiwalfrm** [comment]
could you help me?  I am having problem calling that endpoint.

I invoke: print(solana_client.get_token_accounts_by_owner(my_address, 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA', 'max'))

```
Traceback (most recent call last):
  File "getsolanabalance.py", line 20, in <module>
    print(solana_client.get_token_accounts_by_owner(my_address, 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA', 'max'))
  File "/home/chiwalfrm/.local/lib/python3.8/site-packages/solana/rpc/api.py", line 775, in get_token_accounts_by_owner
    return self.__get_token_accounts(types.RPCMethod("getTokenAccountsByOwner"), str(owner), opts, commitment)
  File "/home/chiwalfrm/.local/lib/python3.8/site-packages/solana/rpc/api.py", line 784, in __get_token_accounts
    if not opts.mint and not opts.program_id:
AttributeError: 'str' object has no attribute 'mint'
```

**Comment by michaelhly** [comment]
You need to use this [option](https://michaelhly.github.io/solana-py/api.html#solana.rpc.types.TokenAccountOpts) to specify your token program.

**Comment by chiwalfrm** [comment]
thanks!  I specified 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' so I don't know why it was throwing the error.  That is the program ID for SPL Token program.  Did I make a syntax error?

`solana_client.get_token_accounts_by_owner(my_address, 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA', 'max')`

**Comment by michaelhly** [comment]
No. You can't specify a plain string.

You have to use the options like `TokenAccountOpts(program_id='TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA')`; here is an example:
https://github.com/michaelhly/solana-py/blob/dd8e1fb91e0d82fa6a241380d8bb516ac8b65583/spl/token/client.py#L134

**Comment by chiwalfrm** [comment]
THANK YOU!  It works now.

**Comment by michaelhly** [comment]
ooof, i don't think so, iirc SPL tokens have to human readable metadata (unlike erc20 tokens). But you can try deserializing thosed data bytes and see what is there:

`data': ['Ii9B9QktgU3mZCAt2+S0ROmkSIWPpH3vtyadWtu/wgT4OjIHSC/gafoWIlrgGukufJF6BK8eqLsIT+02w2iGGAAAAAAAAAAAAQAAADEsftvHNgiiI5GGmo1JNhyLdqbTiDwytzSiFZEENlCRAQAAAAAAAAAAAAAAAN8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 'base64']`

**Comment by f-erdi1990** [comment]
Sorry, but how would i do that? i've tried the decode helper function and just get gibberish...

**Comment by wilburpowery** [comment]
Hi guys, I'm interested in learning more about the programId = `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA` that was shared above. Where can I read more about this?

**Comment by kraussian** [comment]
I've been struggling with this for way too long before finally resorting to calling the JSON-RPC directly through `requests.post()`.

```python
import requests

SOLANA_ENDPOINT = 'https://api.mainnet-beta.solana.com'
SOL_PROGRAM_ID  = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'
SOL_WALLET = 'MyWalletAddress'

payload = {
    'jsonrpc': '2.0',
    'id': 1,
    'method': 'getTokenAccountsByOwner',
    'params': [
        f'{SOL_WALLET}',
        {
            'programId': f'{SOL_PROGRAM_ID}'
        },
        {
            'encoding': 'jsonParsed'
        }
    ]
}
r = post(SOLANA_ENDPOINT, json = payload)
j = r.json()
```

Once you run this, `j['result']['value'][0]` will give you something like:
```python
{'account': {'data': {'parsed': {'info': {'isNative': False,
     'mint': '4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R',
     'owner': '8uxw2Pg7rjjQztUYac7dhoHdxvPEeXG6icL92adythMe',
     'state': 'initialized',
     'tokenAmount': {'amount': '0',
      'decimals': 6,
      'uiAmount': 0.0,
      'uiAmountString': '0'}},
    'type': 'account'},
   'program': 'spl-token',
   'space': 165},
  'executable': False,
  'lamports': 2039280,
  'owner': 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  'rentEpoch': 241},
 'pubkey': 'F9emU4NZM9dgFT5ewCP7PScFUcer6fE3yQCwBP7ariry'}
```

Each of the addresses in `pubkey` will then need to be queried again against something similar to https://github.com/solana-labs/token-list, but I'm stuck at this stage.

**Comment by quazzuk** [comment]
this works for me

```resp = cc.get_token_accounts_by_owner(owner, 
                                      TokenAccountOpts(program_id="TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA", 
                                                       encoding="jsonParsed"))```

**Comment by dandv** [comment]
> I'm interested in learning more about the programId = `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA` that was shared above

@wilburpowery: that is the address of the "Token Program", which can be looked up in the [Solana Explorer](https://explorer.solana.com/):

![Solana Explorer Token Program address](https://user-images.githubusercontent.com/33569/146066397-85904907-d4f2-4a64-b107-f535998ec2eb.png)


In terms of code, it's the `programId` of the `spl-token` program. The documentation is relatively sparse, disjointed and cryptic for such a common use case (finding all tokens owned by an account), but you can see that address at https://spl.solana.com/token#finding-all-token-accounts-for-a-wallet. If you run the example by @codebase011 above and log `tokenAccounts.value[0].account.data`, you'll see `program: 'spl-token'`.

**Comment by giaccomgl** [comment]
Guys But what about fetching DeFi assets (such as LP Tokens, Staking…)? The function you have illustrated works for this kind of data too?

**Comment by CrackerHax** [comment]
Use this to decode metadata:
```
def unpack_metadata_account(data):
    assert(data[0] == 4)
    i = 1
    source_account = base58.b58encode(bytes(struct.unpack('<' + "B"*32, data[i:i+32])))
    i += 32
    mint_account = base58.b58encode(bytes(struct.unpack('<' + "B"*32, data[i:i+32])))
    i += 32
    name_len = struct.unpack('<I', data[i:i+4])[0]
    i += 4
    name = struct.unpack('<' + "B"*name_len, data[i:i+name_len])
    i += name_len
    symbol_len = struct.unpack('<I', data[i:i+4])[0]
    i += 4
    symbol = struct.unpack('<' + "B"*symbol_len, data[i:i+symbol_len])
    i += symbol_len
    uri_len = struct.unpack('<I', data[i:i+4])[0]
    i += 4
    uri = struct.unpack('<' + "B"*uri_len, data[i:i+uri_len])
    i += uri_len
    fee = struct.unpack('<h', data[i:i+2])[0]
    i += 2
    has_creator = data[i]
    i += 1
    creators = []
    verified = []
    share = []
    if has_creator:
        creator_len = struct.unpack('<I', data[i:i+4])[0]
        i += 4
        for _ in range(creator_len):
            creator = base58.b58encode(bytes(struct.unpack('<' + "B"*32, data[i:i+32])))
            creators.append(creator)
            i += 32
            verified.append(data[i])
            i += 1
            share.append(data[i])
            i += 1
    primary_sale_happened = bool(data[i])
    i += 1
    is_mutable = bool(data[i])
    metadata = {
        "update_authority": source_account,
        "mint": mint_account,
        "data": {
            "name": bytes(name).decode("utf-8").strip("\x00"),
            "symbol": bytes(symbol).decode("utf-8").strip("\x00"),
            "uri": bytes(uri).decode("utf-8").strip("\x00"),
            "seller_fee_basis_points": fee,
            "creators": creators,
            "verified": verified,
            "share": share,
        },
        "primary_sale_happened": primary_sale_happened,
        "is_mutable": is_mutable,
    }
    return metadata
```

And this will get metadata:
```
METADATA_PROGRAM_ID = PublicKey('metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s')

def get_nft_pda(mint_key):
    return(PublicKey.find_program_address([b'metadata', bytes(METADATA_PROGRAM_ID), bytes(PublicKey(mint_key))],METADATA_PROGRAM_ID)[0])

def get_nft(mint_key):
    data = base64.b64decode(solana_client.get_account_info(get_nft_pda([mint_key]))['result']['value']['data'][0])
    return(unpack_metadata_account(data))
```

**Comment by ulmentflam** [comment]
For those interested in where all those magic numbers came from in the Metaplex unpack_metadata_account function used in the Metaplex Python Library, checkout https://borsh.io/ and the Metaplex Rust library starting from [here](https://github.com/metaplex-foundation/metaplex-program-library/blob/11be56b934b93ebb2066eefabbf7f4f2adbbe04e/token-metadata/program/src/state.rs#L28). Why the metadata could not just be base64 encoded JSON is beyond me. Blame Solana for using Borsh to "reduce size" and "increase performance" and Metaplex for continuing with that pattern.

**Comment by CrackerHax** [comment]
> For those interested in where all those magic numbers came from in the Metaplex unpack_metadata_account function used in the Metaplex Python Library, checkout https://borsh.io/ and the Metaplex Rust library starting from [here](https://github.com/metaplex-foundation/metaplex-program-library/blob/11be56b934b93ebb2066eefabbf7f4f2adbbe04e/token-metadata/program/src/state.rs#L28). Why the metadata could not just be base64 encoded JSON is beyond me. Blame Solana for using Borsh to "reduce size" and "increase performance" and Metaplex for continuing with that pattern.

Base58 is used rather than base64 to remove similar-looking characters

**Comment by ulmentflam** [comment]
@CrackerHax It's not even the base58 encoding. Solana's JSON parser actually supports base64 decoding or base58 decoding the JSON strings in the requests. However, it does not support deserializing the Borsh encoded data that the Metaplex library uses to encode the data.

**Comment by slhermit** [comment]
When I try to use the examples above 

```
opts = TokenAccountOpts(program_id="TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA", encoding="jsonParsed")
resp = cc.get_token_accounts_by_owner(owner,  opts)
```


I get the error 
`TypeError: argument 'program_id': 'str' object cannot be converted to 'Pubkey'
`

**Comment by slhermit** [comment]
Looking at the changelogs, I could understand why it was failing and make it work....
For reference
```
    opts = TokenAccountOpts(program_id=Pubkey.from_string('TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'))
    resp = SolanaClientInstance.get_token_accounts_by_owner_json_parsed(Pubkey.from_string("walletaddress"),  opts)
```
