### ISSUE TITLE
Solana-py consider solana/web3.js signature is invalid

### ISSUE THREAD

**Issue by Chi-AnTai** [michaelhly/solana-py#49]
We try to pay fee for our user, so we did the following process
1. Set our server as fee payer
2. User partial sign tx in frontend(solana/web3.js)
3. Serialized tx data and pass to our backend
4. Server deserialized tx and add_signer(solana-py)
5. Serialized tx and send raw tx

The step 5 will fail due to solana-py consider the user signature is invalid.
However, if we do step 4 and 5 in JS, it will work.

It looks like JS and Python both use 58encde and 58decode for signatures, so I don't know if I miss something.

**Comment by michaelhly** [comment]
Might be related to https://github.com/michaelhly/solana-py/issues/33. But solana web3js might have updated a lot since I first xopied the tx serde stuff. Will probably need to get the python lib back to parity.

**Comment by Chi-AnTai** [comment]
For my understanding, since fee payer is only the first signature, I hardcode our server signature's position when add_signer. Not 100% sure but I think this part is fine.

**Comment by michaelhly** [comment]
Hey @Chi-AnTai. Can you update to version 0.7.0 and give this another try? Thanks!

**Comment by Chi-AnTai** [comment]
@michaelhly Not 100% sure but it works in our two use cases. Niceeee.

**Comment by michaelhly** [comment]
Going close for now. Please re-open when you can report the new issues. Thanks!

**Comment by crypt0miester** [comment]
hey, sorry for hijacking this after a while. @Chi-AnTai how did you do step no.2 ? of the user partially signing in the frontend? 

would need to be like: 
```
const transaction = new Transaction();
const signedTransaction = await window.solana.signTransaction(transaction);
```
and send the signedTransaction to the backend? please help me as I've been struggling with this for a while now.
