### ISSUE TITLE
Is it possible to generate a 64-byte private key?

### ISSUE THREAD

**Issue by max-block** [michaelhly/solana-py#53]
solana.account.Account generates new accounts, but it's a 32-byte private key.
And I can't import such a key in Sollet wallet. It requires 64-byte key.

Can I generate a new account with this library and next import in into a Sollet wallet?

**Comment by silvercondor** [comment]
adding to this issue.

I'm aware that you can slice the 64 byte key in half and use the 2nd half that in account. but the generated public key is different from what I see in sollet. 

Is there a way I can generate a key pair that is consistent with sollet?

**Comment by michaelhly** [comment]
You need to use the first half.

**Comment by michaelhly** [comment]
Here is an example:
```python3
from solana.account import Account

kp_64 = [ 20, 201, ..., 129 ]
acc = Account(kp_64[:32])
```

**Comment by max-block** [comment]
@michaelhly 

I'm trying to generate a new account with your library and be able to import a new private key to Sollet. 
Here is a example:

```python
from solana.account import Account

new_account = Account()
private_key = [x for x in new_account.secret_key()]

print("address", new_account.public_key())
# address GLkYEGyb6pU7f32VVpVLaMFBewkLPDMqh3bMbTUEhhiW


print("private_key", private_key)
# private_key [103, 5, 162, 252, 15, 154, 245, 91, 130, 8, 179, 133, 212, 224, 136, 130, 129, 69, 67, 159, 64, 25, 196, 78, 128, 17, 187, 212, 23, 139, 18, 183]

# How can I import this new private key to Sollet? It requires 64 bytes, but we have 32 only

```

**Comment by michaelhly** [comment]
> @michaelhly
> 
> I'm trying to generate a new account with your library and be able to import a new private key to Sollet.
> Here is a example:
> 
> ```python
> from solana.account import Account
> 
> new_account = Account()
> private_key = [x for x in new_account.secret_key()]
> 
> print("address", new_account.public_key())
> # address GLkYEGyb6pU7f32VVpVLaMFBewkLPDMqh3bMbTUEhhiW
> 
> 
> print("private_key", private_key)
> # private_key [103, 5, 162, 252, 15, 154, 245, 91, 130, 8, 179, 133, 212, 224, 136, 130, 129, 69, 67, 159, 64, 25, 196, 78, 128, 17, 187, 212, 23, 139, 18, 183]
> 
> # How can I import this new private key to Sollet? It requires 64 bytes, but we have 32 only
> ```

I think you just need to encode the private key in with `base58.b58encode`.

**Comment by max-block** [comment]
> I think you just need to encode the private key with `base58.b58encode`.

Thank you! Now I've realized that it's possible to use a private key in base58 format. It's much more convenient than a string like "[1,2,3....]"

But I still can't understand how I can generate a new account which I can you use with your library and with a Sollet wallet.
As I understand, there is no method in your library to generate a 64-byte private key.
Is it safe to generate it using a python built-in method os.urandom(64)? 

Aslo, the public key in your library and in Sollet, they are different for the same private key.

Here is a code:
```python
import os

import base58
from solana.account import Account

private_key = os.urandom(64)
private_key_base58 = base58.b58encode(private_key).decode("utf-8")
print(private_key_base58)
# 591yJosoAZyaoAa4fFxT7TfSvNaeaEhr45j67wRdbuG26eMM573J6KpuHGxy4bVjfKdPSjaakG712SnFxgcaQFuz

acc = Account(private_key[:32])
print(acc.public_key())
# 9m9qLMYpta6LJiY2Au8aaBZTyYbiqqMTKTWMKrJA3Cjv
```

I imported a new account in Sollet using the private key: 591yJosoAZyaoAa4fFxT7TfSvNaeaEhr45j67wRdbuG26eMM573J6KpuHGxy4bVjfKdPSjaakG712SnFxgcaQFuz

Sollet says that public key for this private is: 2egCYzeNana2T3ePqdALNs7ov3AdRavhxCwqesjVGca4

But you library says that a public key is 9m9qLMYpta6LJiY2Au8aaBZTyYbiqqMTKTWMKrJA3Cjv for the same private. 
What I do wrong?

**Comment by michaelhly** [comment]
@max-block can you try padding your 32 byte key with 0s?

**Comment by michaelhly** [comment]
@max-block Please update to v0.8.0. I just added a helper method to help you do this:
<img width="1275" alt="Screen Shot 2021-04-24 at 4 15 23 PM" src="https://user-images.githubusercontent.com/24895862/115973335-ddddd400-a519-11eb-96f1-aed2f1c3f5ac.png">

**Comment by max-block** [comment]
@michaelhly it works, thank you!

**Comment by Jay54520** [comment]
> @michaelhly it works, thank you!

How to import this to Sollet extension? I can't add the keypair by "Import private key".
