### ISSUE TITLE
transfer problem

### ISSUE THREAD

**Issue by ctycode** [michaelhly/solana-py#60]
Hi,How to transfer tokens from one address to another

**Comment by ctycode** [comment]
> Please try following this example here for now:
> 
> https://github.com/michaelhly/solana-py/blob/815802fbfa6fa5f7c5c1ab1c481b7a7ce3666b2e/tests/integration/test_token_client.py#L110
> 
> I will try to create some new documentation on this..

Okay,so Where is the token written? like `srm`,`ray`
<img width="795" alt="image" src="https://user-images.githubusercontent.com/56985178/117471454-72b8e680-af8a-11eb-9027-3d5ab3bf4d26.png">

**Comment by michaelhly** [comment]
You initialize them here:
https://github.com/michaelhly/solana-py/blob/815802fbfa6fa5f7c5c1ab1c481b7a7ce3666b2e/spl/token/client.py#L79

**Comment by ctycode** [comment]
> solana-py/spl/token/client.py

Hi,I read docs but I don't understand, if I transfer USDC to another address


```
class TransferParams(NamedTuple):
    """Transfer token transaction params."""

    program_id: PublicKey
    """SPL Token program account."""
    source: PublicKey
    """Source account."""
    dest: PublicKey
    """Destination account."""
    owner: PublicKey
    """Owner of the source account."""
    amount: int
    """Number of tokens to transfer."""
    signers: List[PublicKey] = []
    """Signing accounts if `owner` is a multiSig."""
```
`program_id ` What should I fill in?  Token Address? or Associated Token Metadata?
<img width="684" alt="image" src="https://user-images.githubusercontent.com/56985178/117543198-5ed6b880-b04e-11eb-9db0-904177cd35a1.png">
`dest: PublicKey` like this : PublicKey(another address) ?

I look forward to hearing from you

thank you

**Comment by michaelhly** [comment]
```python3
from solana.publickey import PublicKey
from solana.account import Account
from solana.rpc.api import Client
from spl.token.client import Token
from spl.token.contstants import TOKEN_PROGRAM_ID

payer = Account() # Your sol account
usdc_mint = PublicKey(...) # Public key of the usdc mint
conn = Client("https://devnet.solana.com")
usdc_token_client = Token(conn, usdc_mint, TOKEN_PROGRAM_ID, payer)

usdc_token_client.transfer(
            source=PublicKey(...), # PK of USDC token account you're transfering FROM
            dest=PublicKey(...), # PK of USDC token account you're transfering TO
            owner=payer, # Account that owns your source USDC token account
            amount=10000000,
            opts=TxOpts(skip_confirmation=False),
        )
```

**Comment by ctycode** [comment]
> ```python
> from solana.publickey import PublicKey
> from solana.account import Account
> from solana.rpc.api import Client
> from spl.token.client import Token
> from spl.token.contstants import TOKEN_PROGRAM_ID
> 
> payer = Account() # Your sol account
> usdc_mint = PublicKey(...) # Public key of the usdc mint
> conn = Client("https://devnet.solana.com")
> usdc_token_client = Token(conn, usdc_mint, TOKEN_PROGRAM_ID, payer)
> 
> usdc_token_client.transfer(
>             source=PublicKey(...), # PK of USDC token account you're transfering FROM
>             dest=PublicKey(...), # PK of USDC token account you're transfering TO
>             owner=payer, # Account that owns your source USDC token account
>             amount=10000000,
>             opts=TxOpts(skip_confirmation=False),
>         )
> ```

Okay ,thank you 
```
def transfer(
        self,
        source: PublicKey,
        dest: PublicKey,
        owner: Union[Account, PublicKey],
        amount: int,
        multi_signers: Optional[List[Account]] = None,
        opts: TxOpts = TxOpts(),
    ) -> RPCResponse:
```
 Can amount be a decimal?  like `amount: float` ?

**Comment by ctycode** [comment]
> ```python
> from solana.publickey import PublicKey
> from solana.account import Account
> from solana.rpc.api import Client
> from spl.token.client import Token
> from spl.token.contstants import TOKEN_PROGRAM_ID
> 
> payer = Account() # Your sol account
> usdc_mint = PublicKey(...) # Public key of the usdc mint
> conn = Client("https://devnet.solana.com")
> usdc_token_client = Token(conn, usdc_mint, TOKEN_PROGRAM_ID, payer)
> 
> usdc_token_client.transfer(
>             source=PublicKey(...), # PK of USDC token account you're transfering FROM
>             dest=PublicKey(...), # PK of USDC token account you're transfering TO
>             owner=payer, # Account that owns your source USDC token account
>             amount=10000000,
>             opts=TxOpts(skip_confirmation=False),
>         )
> ```

I run this code response this:
```
{'code': -32002, 'message': 'Transaction simulation failed: Error processing Instruction 0: invalid account data for instruction', 'data': {'err': {'InstructionError': [0, 'InvalidAccountData']}, 'logs': ['Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]', 'Program log: Instruction: Transfer', 'Program log: Error: InvalidAccountData', 'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1515 of 200000 compute units', 'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA failed: invalid account data for instruction']}}

```

**Comment by michaelhly** [comment]
Can you post your code?

**Comment by ctycode** [comment]
> Can you post your code?

This is my code
```
sender = Account(bytes(sender[:32]))
usdc_mint = PublicKey(base58.b58decode("2wmVCSfPxGPjrnMMn7rchp4uaeoTqN39mXFC2zhPdri9")) # Public key of the usdc mint
conn = Client("https://solana-api.projectserum.com")
usdc_token_client = Token(conn, usdc_mint, TOKEN_PROGRAM_ID, sender)

usdc_token_client.transfer(
            source=sender.public_key(), # PK of USDC token account you're transfering FROM
            dest=PublicKey(base58.b58decode('3zscPNbmgv6NCtXBSq8bTDpDnbiwKvobXBa8gxQmtXaX')), # PK of USDC token account you're transfering TO
            owner=sender, # Account that owns your source USDC token account
            amount=1000,
            opts=TxOpts(skip_confirmation=False),
        )
```

**Comment by michaelhly** [comment]
Souce cannot be `sender`. It needs to be a usdc token account.

**Comment by michaelhly** [comment]
Use this method to create an account first:
https://michaelhly.github.io/solana-py/spl.html#spl.token.client.Token.create_account

**Comment by ctycode** [comment]
> Use this method to create an account first:
> https://michaelhly.github.io/solana-py/spl.html#spl.token.client.Token.create_account

Okay, I change my code:
```
sender = Account(bytes(sender[:32]))
usdc_mint = PublicKey(base58.b58decode("2wmVCSfPxGPjrnMMn7rchp4uaeoTqN39mXFC2zhPdri9")) # Public key of the usdc mint
conn = Client("https://solana-api.projectserum.com")
source = Token(conn, usdc_mint, TOKEN_PROGRAM_ID, sender)
usdc_token_client = Token(conn, usdc_mint, TOKEN_PROGRAM_ID, sender)

usdc_token_client.transfer(
            source=source.create_account(owner=sender.public_key()), # PK of USDC token account you're transfering FROM
            dest=PublicKey(base58.b58decode('3zscPNbmgv6NCtXBSq8bTDpDnbiwKvobXBa8gxQmtXaX')), # PK of USDC token account you're transfering TO
            owner=sender, # Account that owns your source USDC token account
            amount=1,
            opts=TxOpts(skip_confirmation=False),
        )
```
But response this:
```
Transaction error: {'InstructionError': [1, {'Custom': 2}]}
{'code': -32002, 'message': 'Transaction simulation failed: Error processing Instruction 0: invalid account data for instruction', 'data': {'err': {'InstructionError': [0, 'InvalidAccountData']}, 'logs': ['Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]', 'Program log: Instruction: Transfer', 'Program log: Error: InvalidAccountData', 'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1643 of 200000 compute units', 'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA failed: invalid account data for instruction']}}

```
What's wrong with me?

**Comment by michaelhly** [comment]
Did this suceeded? `source.create_account(owner=sender.public_key()`?

**Comment by ctycode** [comment]
> Did this succeed? `source.create_account(owner=sender.public_key()`?

How to judge whether it is successful or not?

**Comment by ctycode** [comment]
> Did this succeed? `source.create_account(owner=sender.public_key()`?

I run and response this:
<img width="990" alt="image" src="https://user-images.githubusercontent.com/56985178/118513586-71e03b80-b766-11eb-8e71-0de083bf07c7.png">
and I look at：
```https://explorer.solana.com/tx/4EqtspBaAphnepZghqjp9sEdaB1syUkpQXDkb2XcrTHP4YzTeE4jbFueZr3M97Cwxbru3KoWFG24nZKrnf5iLwBf```
<img width="803" alt="image" src="https://user-images.githubusercontent.com/56985178/118514092-d8fdf000-b766-11eb-8e3b-e590d65b08c2.png">
So What’s the problem?

**Comment by novrend** [comment]
I have the same problem.
`raise Exception("Unable to confirm transaction %s" % tx_sig)`
`Exception: Unable to confirm transaction xxx`

**Comment by vcyleung** [comment]
https://www.reddit.com/r/solana/comments/npmfuq/error_send_transaction_spltoken_solana_web3/
It's likely because your destination address has a 0 balance. adding the skip preflight to your options should resolve this. 
`opts=TxOpts(skip_confirmation=False,skip_preflight=True)`

**Comment by vcyleung** [comment]
https://www.reddit.com/r/solana/comments/npmfuq/error_send_transaction_spltoken_solana_web3/

You're probably trying to send USDC to a sol address, you'll need to get the usdc address from the corresponding sol address as the destination. 

![image](https://user-images.githubusercontent.com/15095997/120909457-4fde2880-c643-11eb-9525-3e00593d20fc.png)

**Comment by bibodeng** [comment]
The mint param is not Mint authority owner, it's just **Token Address**, FYI @ctycode

**Comment by MarioProjects** [comment]
Heyo!

I am trying to send a custom SPL token I want to distribute to my holders. This is my code:

```python
from solana.publickey import PublicKey
from solana.account import Account
from solana.rpc.api import Client
from solana.transaction import Transaction
from solana.keypair import Keypair
from spl.token.instructions import transfer, TransferParams
from spl.token.constants import TOKEN_PROGRAM_ID

client = Client("https://api.mainnet-beta.solana.com")

secret_key= [...]
    
sender = Keypair.from_secret_key(bytes(secret_key))
receiver = PublicKey("BkoXyZy4Poam3E97Urd7rmwAvcyC3tZFBap1GHvFCjdS") # TOKEN Account

amount = int(10e6 * 5)

chick_coin = PublicKey("3RXTenk2bvx5cTYY8JrN94EFi3AkYCz9tzJzE7oRhSgf") # Mainnet address
chick_acc = PublicKey("6u4vEaj59irczDu17ydB6E9DTM4XVXZErTVe9LvFyNUG")

# https://michaelhly.github.io/solana-py/spl/intro/
transaction = Transaction().add(transfer(TransferParams(
    source=chick_acc, # PK of token account you're transfering FROM
    dest=receiver, # PK of token account you're transfering TO
    owner=sender.public_key, # Account that owns your source token account
    program_id = TOKEN_PROGRAM_ID,
    amount=amount
)))

res = client.send_transaction(transaction, sender)
```

Obtaining next result:
```
{
  'jsonrpc': '2.0',
  'result': '9cmfZ1zHkxwwUMzHdNAc15Ld2y5Y1PDbRpeuPhLcniPAEFRPTQrHW2akt3cpiYUX5Sgi2rSgTVz3zQPk99jaf2h',
  'id': 2
}
```

But the tokens sometimes are transferred, most of the time no, and never got a bad/error result from the res...

Can you help me? @vcyleung @michaelhly

**Comment by vsdfnvuitsb** [comment]
Hello everyone, 

I didn't expect everyone to encounter the problems I encountered in the development. I checked your problems, and most of them are not your fault, but this open source library solana-py completely violates the code development standards.

 I think The author ( @michaelhly )  of this open source library should have absolutely no idea how solana works. His coding style is comparable to that of Ukrainian neo-Nazis, which makes no sense.

 I strongly recommend everyone to use the Javascript version of the open source library solana-web3, which can solve all your problems. @MarioProjects @vcyleung

**Comment by ZenRepublic** [comment]
I get this error:

solana.rpc.core.RPCException: {'code': -32002, 'message': 'Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.', 'data': {'accounts': Non
e, 'err': 'AccountNotFound', 'logs': [], 'unitsConsumed': 0}}

so I assume my owner parameter is incorrect
I am providing Keypair but it asks me Union[Keypair,PublicKey]
Could you help me out please?

`async def spl_transaction(token_address,receiver_key, amount):
    async with AsyncClient(client_network) as client:
        account = dbAccounts.get_zen_wallet()
        byte_array = base58.b58decode(account["private_key"])
        slicer = slice(32)
        byte_array32 = byte_array[slicer]

        # sender = Keypair.from_secret_key(account['secret_key'].encode("latin-1"))
        sender = Keypair.from_seed(byte_array32)
        token_client = AsyncToken(client,PublicKey(token_address),TOKEN_PROGRAM_ID,sender)
        source_account = await token_client.create_account(owner=sender.public_key)
        print(sender)
        try:
            response = await token_client.transfer(
                source= source_account,
                dest=PublicKey(receiver_key),
                owner=sender,
                amount=int(amount*pow(10,9)),
                opts=TxOpts(skip_confirmation=False)
            )
            print(response)
            if 'result' in response:
                message = "View the transaction here: https://explorer.solana.com/tx/{}".format(response['result'])
                return message
            else:
                return None

        except Exception as e:
            print('error:', e)
            return None`

**Comment by ZenRepublic** [comment]
after downgrading to solana version 0.23 i am able to do token_client.create_account, but....

in transfer function, my "owner" seems to be incorrect. If i just enter the keypair, it says im missing something, incorrect account

pls help im desperate

**Comment by Nacbotics-dev** [comment]
![image](https://user-images.githubusercontent.com/93852266/202246727-ea7e315f-5346-4f09-bf2d-9b9ff5b1b286.png)

 this is how i solved mine.

first check if we have a token account, if not we create one

we also get a the token account from the sender.

took me hours to figure this out through trial and error, I'm available for further clarification

**Comment by zed14526** [comment]
> Please try following this example here for now:
> 
> https://github.com/michaelhly/solana-py/blob/815802fbfa6fa5f7c5c1ab1c481b7a7ce3666b2e/tests/integration/test_token_client.py#L110
> 
> I will try to create some new documentation on this..

hey what did you install to have the publickey import ? 
![image](https://github.com/michaelhly/solana-py/assets/154510070/8c0151eb-16ff-4b65-9767-d5a8262d45de)
 i have this issues 
thanks.

**Comment by michaelhly** [comment]
> > Please try following this example here for now:
> > https://github.com/michaelhly/solana-py/blob/815802fbfa6fa5f7c5c1ab1c481b7a7ce3666b2e/tests/integration/test_token_client.py#L110
> > 
> > I will try to create some new documentation on this..
> 
> hey what did you install to have the publickey import ? ![image](https://private-user-images.githubusercontent.com/154510070/292671285-8c0151eb-16ff-4b65-9767-d5a8262d45de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5ODA0MTgsIm5iZiI6MTcwMzk4MDExOCwicGF0aCI6Ii8xNTQ1MTAwNzAvMjkyNjcxMjg1LThjMDE1MWViLTE2ZmYtNGI2NS05NzY3LWQ1YTgyNjJkNDVkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIzMFQyMzQ4MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDE3YzBjY2U4N2ZlMDI0ZmFmOTM3ODJjYjViYWE4ZjM3ZDRmZGYzZDUyNmE4ZWU0ZmZlNGJkODJkNzJlMzE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Yc1vXFasEAGz1SNahA75mr1qOMFIm551pc6FqQxIeug) i have this issues thanks.

See https://kevinheavey.github.io/solders/api_reference/pubkey.html

**Comment by Sidhi-iTechnolabs** [comment]
> ![image](https://user-images.githubusercontent.com/93852266/202246727-ea7e315f-5346-4f09-bf2d-9b9ff5b1b286.png)
> 
> this is how i solved mine.
> 
> first check if we have a token account, if not we create one
> 
> we also get a the token account from the sender.
> 
> took me hours to figure this out through trial and error, I'm available for further clarification

can you please guide me about this..

File "/home/itechnolabs-17/venv/lib/python3.12/site-packages/solana/rpc/providers/core.py", line 98, in _parse_raw
    raise RPCException(parsed)
solana.rpc.core.RPCException: SendTransactionPreflightFailureMessage { message: "Transaction simulation failed: Error processing Instruction 0: invalid account data for instruction", data: RpcSimulateTransactionResult(RpcSimulateTransactionResult { err: Some(InstructionError(0, InvalidAccountData)), logs: Some(["Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]", "Program log: Instruction: TransferChecked", "Program log: Error: InvalidAccountData", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1357 of 200000 compute units", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA failed: invalid account data for instruction"]), accounts: None, units_consumed: Some(1357), return_data: None, inner_instructions: None, replacement_blockhash: None }) }

I m getting this error.

**Comment by Nacbotics-dev** [comment]
> > ![image](https://user-images.githubusercontent.com/93852266/202246727-ea7e315f-5346-4f09-bf2d-9b9ff5b1b286.png)
> > this is how i solved mine.
> > first check if we have a token account, if not we create one
> > we also get a the token account from the sender.
> > took me hours to figure this out through trial and error, I'm available for further clarification
> 
> can you please guide me about this..
> 
> File "/home/itechnolabs-17/venv/lib/python3.12/site-packages/solana/rpc/providers/core.py", line 98, in _parse_raw raise RPCException(parsed) solana.rpc.core.RPCException: SendTransactionPreflightFailureMessage { message: "Transaction simulation failed: Error processing Instruction 0: invalid account data for instruction", data: RpcSimulateTransactionResult(RpcSimulateTransactionResult { err: Some(InstructionError(0, InvalidAccountData)), logs: Some(["Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]", "Program log: Instruction: TransferChecked", "Program log: Error: InvalidAccountData", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1357 of 200000 compute units", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA failed: invalid account data for instruction"]), accounts: None, units_consumed: Some(1357), return_data: None, inner_instructions: None, replacement_blockhash: None }) }
> 
> I m getting this error.

can you share your code?

**Comment by sammiykay** [comment]
`from anchorpy import Provider, Wallet
from solders.pubkey import Pubkey
from solders.keypair import Keypair
from solana.rpc.async_api import AsyncClient
from solana.transaction import Transaction
from spl.token.instructions import transfer_checked, get_associated_token_address, TransferCheckedParams
from spl.token.constants import TOKEN_PROGRAM_ID

import asyncio

# Initialize Solana Client (Mainnet RPC)
async def main():
    client = AsyncClient("https://api.mainnet-beta.solana.com")

    # Load Sender's Wallet (Use a secure method to store your private key)
    private_key = ""
    sender = Keypair.from_base58_string(private_key)
    sender_pubkey = sender.pubkey()
    print(f"Sender Public Key: {sender_pubkey}")

    # Receiver's Wallet Address
    receiver_pubkey = `Pubkey.from_string("")`

    # USDT Token Mint Address on Solana (Mainnet)
    usdt_mint = Pubkey.from_string("Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB")

    # Associated Token Accounts for Sender and Receiver
    sender_usdt_account = get_associated_token_address(sender_pubkey, usdt_mint)
    receiver_usdt_account = get_associated_token_address(receiver_pubkey, usdt_mint)

    print(f"Sender USDT Account: {sender_usdt_account}")
    print(f"Receiver USDT Account: {receiver_usdt_account}")

    # Function to get token balance safely
    async def get_token_balance(account):
        try:
            balance_resp = await client.get_token_account_balance(account)
            if hasattr(balance_resp, 'value') and balance_resp.value:
                return int(balance_resp.value.amount)
            else:
                return 0
        except Exception as e:
            print(f"Error fetching balance for {account}: {e}")
            return 0

    # Fetch Balances
    sender_balance = await get_token_balance(sender_usdt_account)
    receiver_balance = await get_token_balance(receiver_usdt_account)

    print(f"Sender USDT Balance: {sender_balance}")
    print(f"Receiver USDT Balance: {receiver_balance}")

    # Amount to Send (USDT has 6 decimals, so multiply by 10^6)
    amount_usdt = 0.00045 # 1 USDT
    amount = int(amount_usdt * 10**6)  # Convert to smallest unit
    print(f"Sending {amount_usdt} USDT ({amount} lamports)")
    print(sender_balance)
    # Ensure sender has enough balance
    if sender_balance < amount:
        print("Insufficient balance!")
        await client.close()
        return

    # Create Transfer Instruction
    instruction = transfer_checked(
        TransferCheckedParams(
            program_id=TOKEN_PROGRAM_ID,
            source=sender_usdt_account,
            mint=usdt_mint,
            dest=receiver_usdt_account,
            owner=sender_pubkey,
            amount=amount,
            decimals=6
        )
    )

    # Create and Sign Transaction
    transaction = Transaction()
    transaction.add(instruction)

    try:
        # Send Transaction
        result = await client.send_transaction(transaction, sender)
        print("Transaction Successful! Transaction Signature:", result)
    except Exception as e:
        print("An error occurred:", e)
    finally:
        await client.close()

asyncio.run(main())
`


i got this error
An error occurred: SendTransactionPreflightFailureMessage { message: "Transaction simulation failed: Error processing Instruction 0: invalid account data for instruction", data: RpcSimulateTransactionResult(RpcSimulateTransactionResult { err: Some(InstructionError(0, InvalidAccountData)), logs: Some(["Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]", "Program log: Instruction: TransferChecked", "Program log: Error: InvalidAccountData", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2984 of 200000 compute units", "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA failed: invalid account data for instruction"]), accounts: None, units_consumed: Some(2984), return_data: None, inner_instructions: None }) }

please can someone help me out
