### ISSUE TITLE
How to transfer SOL to an empty accounts?

### ISSUE THREAD

**Issue by max-block** [michaelhly/solana-py#61]
When I transfer SOL to an account with some amount of SOL, there are no any problems.

But when I try to transfer to an ampty account, I have such an error:

`{'code': -32002, 'message': 'Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.', 'data': {'err': 'AccountNotFound', 'logs': []}}`

As I understand, it's necessary to create an account first. I try to do it like this:
```python
client = Client(ENDPOINT)
acc = commons.get_account(PRIVATE_KEY)
tx = Transaction(fee_payer=acc.public_key())
tx.add(
    create_account(
        CreateAccountParams(
            from_pubkey=acc.public_key(),
            new_account_pubkey=PublicKey(ACCOUNT_1),
            lamports=1,
            space=1,
            program_id=SYS_PROGRAM_ID,
        )
    )
)
res = client.send_transaction(tx, acc)
print(res)
```

But it fails like this:
`{'code': -32002, 'message': 'Transaction simulation failed: Error processing Instruction 0: missing required signature for instruction', 'data': {'err': {'InstructionError': [0, 'MissingRequiredSignature']}, 'logs': ['Program 11111111111111111111111111111111 invoke [1]', "Allocate: 'to' account Address { address: 7tDBKbR67f5fzTW8h5CUffa9FQXZhmEPY253wgs34uAe, base: None } must sign", 'Program 11111111111111111111111111111111 failed: missing required signature for instruction']}}`

But I want to transfer SOL to an account which is empty I don't know its private key, so I can't sign it. So, how can I transfer SOL to an empty account?

**Comment by michaelhly** [comment]
You have to create an account, and then transfer SOL. It should be two separate instructions inside a transaction. Does that make sense? Please reference the example in this notebook:
https://github.com/michaelhly/solana-py/blob/master/notebooks/SendTransaction.ipynb

You can run `make notebook` to run the code block in the notebook, as well as add your own code :).

**Comment by max-block** [comment]
Sorry, it's my mistake. I confused a mainet-beta and testnet endpoint, so there was no enough SOL on balance.

It's not necessary to create an account before transfering SOL. It's OK to transfer SOL on an empty account.
This code works fine:
```python
client = Client(node)
tx = Transaction(fee_payer=acc.public_key())
ti = transfer(TransferParams(from_pubkey=acc.public_key(), to_pubkey=PublicKey(recipient_address), lamports=lamports))
tx.add(ti)
res = client.send_transaction(tx, acc)
```
