### ISSUE TITLE
Library uses deprecated commitment levels

### ISSUE THREAD

**Issue by LucasBruder** [michaelhly/solana-py#72]
https://docs.solana.com/developing/clients/jsonrpc-api#configuring-state-commitment
https://github.com/solana-labs/solana-web3.js/blob/62513cdee2ca0c4f350e811a982ca13731201a9f/src/connection.ts#L212

New commitment levels are:
finalized, confirmed, and processed.

This seems like a breaking change

**Comment by michaelhly** [comment]
I will pick this up soon.

**Comment by mschneider** [comment]
We noticed that in a lot of our trading bots we need to set the commitment level on every rpc call to 'processed'. In JS we have the ability to set this directly on the Connection object, which is the counterpart of Client. This allows us to have the code look pretty normal, and not specify the commitment on every rpc call. Might be worth adding, if you anyways plan to retouch all the confirmation args.
