### ISSUE TITLE
Invalid param: not a v2.0 Token account

### ISSUE THREAD

**Issue by V-kik** [michaelhly/solana-py#75]
Hi I am trying to use this python wrapper to query information about my solana wallet using the endpoint 
"https://solana-api.projectserum.com"

The response when querying the account balance is:
{'jsonrpc': '2.0',
 'error': {'code': -32602,
  'message': 'Invalid param: not a v2.0 Token account'},
 'id': 20}
 
 What is my mistake here?

**Comment by keyserjaya** [comment]
bump, have u found the solution?
