### ISSUE TITLE
getConfirmedSignaturesForAddress2 -> getConfirmedSignatures

### ISSUE THREAD

**Issue by hareeshnagaraj** [michaelhly/solana-py#76]
Hi all! Just wondering if an update to this function was in the works? I noticed this is going to be deprecated from the official Solana docs:

https://docs.solana.com/developing/clients/jsonrpc-api#getconfirmedsignaturesforaddress2

It appears the latest on master only has the older version:
https://github.com/michaelhly/solana-py/blob/master/solana/rpc/api.py#L266

**Comment by michaelhly** [comment]
Thanks for catching this. Will update this soon!

**Comment by hareeshnagaraj** [comment]
thanks @michaelhly!!
