### ISSUE TITLE
Is there a asynchronous version of solana-py?

### ISSUE THREAD

**Issue by johnsonchak** [michaelhly/solana-py#80]
Is there a asynchronous version of solana-py?

**Comment by kevinheavey** [comment]
There is not. A guy called buffalu said a while ago that he was working on adding async support but I don't know him. I might also work on it btw as I think it's important

**Comment by michaelhly** [comment]
No, there is not. But you can probably wrap the RPC calls with threads as a workaround.

**Comment by kevinheavey** [comment]
Update: I am working on it this weekend
