### ISSUE TITLE
LICENSE file not included in PyPI packages

### ISSUE THREAD

**Issue by kevinheavey** [michaelhly/solana-py#84]
The LICENSE file isn't included in the files that get uploaded to PyPI (you'll see if you download and unpack the .tar.gz file from here https://pypi.org/project/solana/#files). This is Bad from a legal perspective and causes problems for tools like conda.

However I couldn't replicate this behaviour: I tried uploading the package to TestPyPI and the LICENSE file was included fine https://test.pypi.org/project/solana1/0.11.0/#files.
What command is being run to upload to PyPI? Is it possible it's using some older version of setuptools or something?

**Comment by michaelhly** [comment]
I run `make publish` to publish the package to pypi:
https://github.com/michaelhly/solana-py/blob/e2d53a61fd4bfd30a8d3726aa87398c04b248b38/Makefile#L19

**Comment by kevinheavey** [comment]
Ok, can you check if the source distribution has a LICENCE file on your machine? It does on mine.

You'll want to run :
```bash
rm -rf dist
python setup.py sdist
cd dist
tar -xzf solana-0.11.0.tar.gz
ls solana-0.11.0/LICENSE # this exists on my machine
```

**Comment by michaelhly** [comment]
This should fix it:
https://github.com/michaelhly/solana-py/commit/077bd9943d0475d8234822b4405275bb3d75bfc7
