### ISSUE TITLE
LICENSE file missing again in 0.11.2

### ISSUE THREAD

**Issue by kevinheavey** [michaelhly/solana-py#86]
The LICENSE file isn't in the PyPI distribution for 0.11.2. When I run `python setup.py sdist` it appears in the .tar.gz file. @michaelhly does it appear for you?

I'm using setuptools v57.0.0 and twine v3.4.2.

**Comment by michaelhly** [comment]
Yes. It's missing again :(.

**Comment by kevinheavey** [comment]
Does it appear in the tarball when you run `python setup.py sdist` on your machine? I feel like this is likely a setuptools version issue

**Comment by kevinheavey** [comment]
The conda build is failing :( https://github.com/conda-forge/solana-feedstock/pull/1

**Comment by michaelhly** [comment]
> Does it appear in the tarball when you run `python setup.py sdist` on your machine? I feel like this is likely a setuptools version issue

It does not. But I thought it did in `0.11.1`.

**Comment by michaelhly** [comment]
I'll need to take another look..

**Comment by kevinheavey** [comment]
> > Does it appear in the tarball when you run `python setup.py sdist` on your machine? I feel like this is likely a setuptools version issue
> 
> It does not. But I thought it did in `0.11.1`.

yeah I think it's because we removed `include_package_data=True`. But we don't want to put that back as it'll make `py.typed` disappear again. And we don't need it back because the LICENSE file gets included on my machine without `include_package_data=True`

**Comment by michaelhly** [comment]
Oh. So it is included on your machine?

**Comment by kevinheavey** [comment]
Yep. Using setuptools v57.0.0

**Comment by michaelhly** [comment]
Looks like it was b/c my `setuptools` was out of date. Just release 0.11.3, it now has the LICENSE file included.
