### ISSUE TITLE
@kevinheavey, Hi Kevin, I have a problem when testing Account()

### ISSUE THREAD

**Issue by giftedchen** [michaelhly/solana-py#87]
I tried to input the priavte key string such as "W3VVNx2buS7YYYYYYYYYPksrmDJydgKXXXXXXXXXXXXXXXXbFtyZp4CVxp47eCHCvpZPPPPK2GYFaQvA"(exported from phamton wallet) into Account() to initialize my Account to transfer tokens, but it failed. It seems the the Account() needs a keypair which is a int array such as
 keypair = [
    ...     90, 249, 112, 214, 86, 235, 20, 215, 175, 33, 227, 50, 72, 214, 59, 49,
    ...     38, 161, 99, 83, 107, 188, 57, 48, 119, 189, 46, 148, 160, 214, 239, 148,
    ...     219, 250, 20, 106, 35, 41, 118, 107, 89, 96, 195, 15, 153, 248, 223, 6,
    ...     46, 71, 142, 92, 169, 240, 177, 106, 86, 194, 21, 62, 29, 222, 206, 82]

SO can you help me out to import a Account right with a priavte key string?

many thanks!

**Comment by vcyleung** [comment]
Try asking the phantom discord / faqs and searching the solana subreddit, first. [Accounts ](https://solana-labs.github.io/solana-web3.js/classes/Account.html) have been deprecated and are moving towards [keypairs](https://solana-labs.github.io/solana-web3.js/classes/Keypair.html), as you've previously noticed. You'll need to see how phantom allows you to get access to the keypair, and if phantom is pursuing the [multichain wallet](https://venturebeat.com/2021/07/14/phantom-raises-9m-for-its-mainstream-multi-chain-crypto-wallet/) approach their private key may not be a solana specific key. That private key may only provide access to the wallet but not the underlying token accounts.
