### ISSUE TITLE
get_token_accounts_by_owner() does not take "encoding" as optional argument

### ISSUE THREAD

**Issue by GitTimmerd** [michaelhly/solana-py#88]
Hi,

The get_token_accounts_by_owner() function does not have the functionality to choose the encoding as optional argument, unlike in the official API function: https://docs.solana.com/developing/clients/jsonrpc-api#gettokenaccountsbyowner
In many other functions in the library this functionality is there, is there a possibility that this can also be added to this function? Thanks!

**Comment by KurtCMrD** [comment]
@michaelhly  I can pick this up. Can you assign it to me, please?

**Comment by michaelhly** [comment]
> @michaelhly I can pick this up. Can you assign it to me, please?

Sorry. Just saw this. Assigned to you :)
