### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Mitolius** [michaelhly/solana-py#90]
Hi,

First of all, sorry for this "issue" which is not really an "issue" but a bunch of questions by a noob :p
I would like to make a python program to interact with pool or farm from different protocols on Solana DEX.

1) Can I achieve this using solana-py (I think yes)
2) I read the doc but there is no examples for what I want to achieve, do you have some links to educate myself ?
3) I saw in the doc that smart contract ID on Solana are called "Program ID", is it the same as a pool/farm address and so we could simply connect to RPC, and make simple transaction on that "Program ID" to swap token for example ? 

Thank you for you answers.

Regards,
Mitolius

**Comment by deep0072** [comment]
I also want to know like as a python-dev can I get a job in the blockchain domain?

**Comment by michaelhly** [comment]
Please check out https://github.com/kevinheavey/anchorpy for program specific interactions.
