### ISSUE TITLE
get_signatures_for_address() returns 'Method not found'

### ISSUE THREAD

**Issue by AkiYoneyama** [michaelhly/solana-py#92]
Hi,

I noticed that get_signatures_for_address() has come to return 'Method not found' since yesterday.
My code is as follows, which worked properly several days ago: 
```
from solana.rpc.api import Client

url = "https://api.mainnet-beta.solana.com"
client = Client(url)

account = "8tnpAECxAT9nHBqR1Ba494Ar5dQMPGhL31MmPJz1zZvY"
response = client.get_signatures_for_address(account)
print(response)
```

Result:
```
{'jsonrpc': '2.0',
 'error': {'code': -32601, 'message': 'Method not found'},
 'id': 1}
```

I have tried versions `0.12.0` and `0.12.1` but the result did not change.
Is there something wrong with my code?
If not, is there any Solana network update affecting it?

The minimum code which I extract from the implementation of `get_signatures_for_address` is as follows, but this also gives the same result:

```
import os
import json
import requests

url = "https://api.mainnet-beta.solana.com"
endpoint_uri = os.environ.get("SOLANARPC_HTTP_URI", url)

method = "getSignaturesForAddress"
account = "8tnpAECxAT9nHBqR1Ba494Ar5dQMPGhL31MmPJz1zZvY"
opts = {"limit": 1}
params = (account, opts)

headers = {"Content-Type": "application/json"}
data = json.dumps({"jsonrpc": "2.0", "id": 1, "method": method, "params": params})
data_kwarg = "data"
request_kwargs = {"url": endpoint_uri, "headers": headers, data_kwarg: data}

raw_response = requests.post(**request_kwargs)
raw_response.raise_for_status()
decoded = json.loads(raw_response.text)
print(decoded)
```

**Comment by michaelhly** [comment]
Please use `get_signatures_for_address2`. `get_signatures_for_address` is currently not supported on mainnet.

**Comment by AkiYoneyama** [comment]
Oh, I see. I've gotten the correct output by using `get_confirmed_signature_for_address2`. Thanks!

**Comment by OkarFabianTheWise** [comment]
Why is this method not working again.. I want to get only latest transaction signatures and not older ones
