### ISSUE TITLE
How to interact with smart contracts

### ISSUE THREAD

**Issue by wuyi771** [michaelhly/solana-py#94]
I can send SOL, but I don’t know how to interact with the contract. There is no ABI, and the contract address has no code.

**Comment by michaelhly** [comment]
@kevinheavey is working on an [Anchor](https://github.com/project-serum/anchor) client for Python. He'll have something ready for you soon...

If you don't want to wait, you have to figure out how to serialize data into binary manually to interact with Solana programs. Example:
https://github.com/michaelhly/solana-py/tree/master/spl/token

**Comment by dangell7** [comment]
Is there a Solana web3.py repo? I dont need all the extra stuff.

Anchor reminds me of ganache/drizzle/truffle which is cool but a lot of us don't need all that.

**Comment by kevinheavey** [comment]
> Is there a Solana web3.py repo? I dont need all the extra stuff.

Good news! You’re in the right place

**Comment by crypt0miester** [comment]
any updates on the python anchor client?

**Comment by kevinheavey** [comment]
> any updates on the python anchor client?
> 
> would love to be able to create candy machine.

With the caveat that I’m just some guy, I’m targeting this month for a first release

**Comment by crypt0miester** [comment]
> With the caveat that I’m just some guy, I’m targeting this month for a first release

you already did an amazing job with the solana-py.

you can do it mate. I'm quite jealous of what is happening in the js libraries. 

my platform depends on this. cheers.

**Comment by kevinheavey** [comment]
@crypt0miester I'm curious about what you're working on, is there a way I can contact you?

**Comment by crypt0miester** [comment]
hello@artz.ai
we are building an open nft marketplace based on metaplex api.

I've done the minting one nft part. would be awesome if we can host drops (candy machine) on our system.

**Comment by jacekv** [comment]
I created a repo on different topics. Still work in progress, but it covers also on how to call functions in a Solana program. Have a look here: https://github.com/jacekv/Solana-Intro
The `function_calls` dir contains an example of a calculator program which is able to add or sub to number, and a Python client calling the functions.
