### ISSUE TITLE
Initializing spl.token.client.Token()

### ISSUE THREAD

**Issue by santhoshnarayan** [michaelhly/solana-py#95]
I'm guessing the `program_id` is the PublicKey of the program for minting, but what is the first PublicKey (pubkey) in reference to?

```
class Token(_TokenCore):  # pylint: disable=too-many-public-methods
    """An ERC20-like Token."""

    def __init__(self, conn: Client, pubkey: PublicKey, program_id: PublicKey, payer: Account) -> None:
```

**Comment by michaelhly** [comment]
No. `pubkey` is the mint, and `program_id` is 
https://michaelhly.github.io/solana-py/spl.html#spl.token.constants.TOKEN_PROGRAM_ID
